### ISSUE TITLE
Package Project Failing - UE 5.1, Cesium for unreal 1.21.0, Ubuntu 20.04

### ISSUE THREAD

**Issue by wurrego** [CesiumGS/cesium-unreal#1023]
Went to package my project today for Linux on an Ubuntu 20.04 system. 

Just upgraded my Cesium for Unreal plugin to v1.21.0, unfortunetly the cook stage is failing. Build log excerpt below. Appreciate any advice on how to further troubleshoot this.
 _Of note is the following lines from that excerpt:_

```
x00007fed31637966 libUnrealEditor-CesiumEditor.so!async::detail::task_func<CesiumAsync::CesiumImpl::ImmediateScheduler<CesiumAsync::CesiumImpl::QueuedScheduler>, async::detail::continuation_exec_func<CesiumAsync::CesiumImpl::ImmediateScheduler<CesiumAsync::CesiumImpl::QueuedScheduler>, async::task<std::__1::shared_ptr<CesiumAsync::IAssetRequest> >, CesiumIonClient::Response<CesiumIonClient::Profile>, CesiumIonClient::Connection::me() const::$_2, std::__1::integral_constant<bool, true>, false>, CesiumIonClient::Response<CesiumIonClient::Profile> >::cancel(async::detail::task_base*, std::exception_ptr&&)()
0x00007fed3c104033 libUnrealEditor-CesiumRuntime.so!async::task_run_handle::~task_run_handle() [/mnt/nvme1n1p1/UE5/ue5-projects/Cerberus/Plugins/CesiumForUnreal/Source/ThirdParty/include/async++/scheduler.h:121]
0x00007fed3c1a86e5 libUnrealEditor-CesiumRuntime.so!async::fifo_scheduler::~fifo_scheduler()()
0x00007fed3c16f6b7 libUnrealEditor-CesiumRuntime.so!CesiumAsync::AsyncSystem::~AsyncSystem() [/mnt/nvme1n1p1/UE5/ue5-projects/Cerberus/Plugins/CesiumForUnreal/Source/ThirdParty/include/CesiumAsync/AsyncSystem.h:35]
**0x00007fee9d1888a7 libc.so.6!UnknownFunction(0x468a6)**
```

==== Build Log Excerpt ====
LogShaderCompilers: Display: Shaders left to compile 0
Signal 11 caught.
Malloc Size=262146 LargeMemoryPoolOffset=262162
CommonUnixCrashHandler: Signal=11
=== Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000030
Fatal error!

0x00007feea8c98fc4 libpthread.so.0!pthread_mutex_lock(+0x4)
0x00007feea8a151b6 libUnrealEditor-Core.so!std::__1::mutex::lock()(+0x5)
0x00007fed3166fffe libUnrealEditor-CesiumEditor.so!async::fifo_scheduler::schedule(async::task_run_handle)()
0x00007fed31672ce3 libUnrealEditor-CesiumEditor.so!CesiumAsync::CesiumImpl::QueuedScheduler::schedule(async::task_run_handle)()
0x00007fed315b47c6 libUnrealEditor-CesiumEditor.so!CesiumAsync::CesiumImpl::ImmediateScheduler<CesiumAsync::CesiumImpl::QueuedScheduler>::schedule(async::task_run_handle) [/mnt/nvme1n1p1/UE5/ue5-projects/Cerberus/Plugins/CesiumForUnreal/Source/ThirdParty/include/CesiumAsync/Impl/ImmediateScheduler.h:25]
0x00007fed315b46c5 libUnrealEditor-CesiumEditor.so!void async::detail::task_base::run_continuation<CesiumAsync::CesiumImpl::ImmediateScheduler<CesiumAsync::CesiumImpl::QueuedScheduler> >(CesiumAsync::CesiumImpl::ImmediateScheduler<CesiumAsync::CesiumImpl::QueuedScheduler>&, async::detail::ref_count_ptr<async::detail::task_base>&&) [/mnt/nvme1n1p1/UE5/ue5-projects/Cerberus/Plugins/CesiumForUnreal/Source/ThirdParty/include/async++/task_base.h:101]
0x00007fed315b26ec libUnrealEditor-CesiumEditor.so!void async::detail::continuation_vector::flush_and_lock<async::detail::task_base::run_continuations()::'lambda'(async::detail::ref_count_ptr<async::detail::task_base>)>(async::detail::task_base::run_continuations()::'lambda'(async::detail::ref_count_ptr<async::detail::task_base>)&&) [/mnt/nvme1n1p1/UE5/ue5-projects/Cerberus/Plugins/CesiumForUnreal/Source/ThirdParty/include/async++/continuation_vector.h:219]
0x00007fed31637966 libUnrealEditor-CesiumEditor.so!async::detail::task_func<CesiumAsync::CesiumImpl::ImmediateScheduler<CesiumAsync::CesiumImpl::QueuedScheduler>, async::detail::continuation_exec_func<CesiumAsync::CesiumImpl::ImmediateScheduler<CesiumAsync::CesiumImpl::QueuedScheduler>, async::task<std::__1::shared_ptr<CesiumAsync::IAssetRequest> >, CesiumIonClient::Response<CesiumIonClient::Profile>, CesiumIonClient::Connection::me() const::$_2, std::__1::integral_constant<bool, true>, false>, CesiumIonClient::Response<CesiumIonClient::Profile> >::cancel(async::detail::task_base*, std::exception_ptr&&)()
0x00007fed3c104033 libUnrealEditor-CesiumRuntime.so!async::task_run_handle::~task_run_handle() [/mnt/nvme1n1p1/UE5/ue5-projects/Cerberus/Plugins/CesiumForUnreal/Source/ThirdParty/include/async++/scheduler.h:121]
0x00007fed3c1a86e5 libUnrealEditor-CesiumRuntime.so!async::fifo_scheduler::~fifo_scheduler()()
0x00007fed3c16f6b7 libUnrealEditor-CesiumRuntime.so!CesiumAsync::AsyncSystem::~AsyncSystem() [/mnt/nvme1n1p1/UE5/ue5-projects/Cerberus/Plugins/CesiumForUnreal/Source/ThirdParty/include/CesiumAsync/AsyncSystem.h:35]
0x00007fee9d1888a7 libc.so.6!UnknownFunction(0x468a6)
0x00007fee9d188a60 libc.so.6!exit(+0x1f)
0x00007fee9d16608a libc.so.6!__libc_start_main(+0xf9)
0x0000000000235139 UnrealEditor!_start()
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Took 114.87109140000001s to run UnrealEditor, ExitCode=139

**Comment by kring** [comment]
@wurrego how have you installed the plugin? Is it from the Epic Marketplace? Do you have the same problem with the Cesium for Unreal Samples project?

**Comment by wurrego** [comment]
Thanks @kring for the response and help again.

- The plugin is compiled from source, following the instructions without deviation
- The compilation was done on a fresh git clone of cesium for unreal/ue5-main branch the day after the 1.21.0 release
- I copy the plugin folder into both Engine/Plugins/Marketplace and my-project/Plugins folder

As for the Cesium for Unreal Samples project, i have not beeen succesful with getting that project to open.
- After I close cesium-unreal-samples and copy in the compiled CesiumForUnreal plugin into Plugins. When i attempt to open that project I get the following error at 78% "Plugin CesiumForUnreal failed to load because module CesiumRuntime could not be loaded. There may be an operating system error or the module may not be properly set up.
- The console log shows the following error when the alert window is presented:
[2023.01.09-13.36.52:948][  0]LogCore: Warning: dlopen failed: libUnrealEditor-SunPosition.so: cannot open shared object file: No such file or directory

Typically I see this error when I open a project that includes CesiumForUnreal Plugin that has been just built or copied in, and my resolution is to run make on the console.  Since the cesium samples project does not include a Makefile, I am unable to resolve the error.

Thanks again for the help, I am free today to try any suggestions

-

**Comment by kring** [comment]
Support for the Unreal Editor on Linux is shaky at best. You're definitely in unexplored territory. A few things:

1. UE 5.1 seems to have a bug where it embeds an incorrect RPATH to the SunPosition plugin. That's the cause of the problem you're seeing in the samples. I started setting up an automated builds for Cesium for Unreal on Linux, and was able to fix this by rewriting the RPATH after it was built by using `patchelf`. You can see how here: https://github.com/CesiumGS/cesium-unreal/compare/linux-editor#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R368
2. I'm not sure why you wouldn't have the problem above with your own project, only with the Samples. Most likely you're just not getting that far. So it's probably worthwhile to get the Samples working first, and then go back to your project.
3. You should avoid having the plugin in _both_ the engine plugins dir and in your project. I suggest only putting it in the engine plugins dir.
4. The Samples project doesn't have a makefile because it's blueprints-only. You can fix this by coping the plugin's Documentation/Source directory into your project's Source directory. But generally you shouldn't need to do this (and it may create new problems, so I suggest getting the project working Blueprints-only first).

**Comment by wurrego** [comment]
Thanks @kring that was helpful. 

I delete my-project/Plugins/CesiumForUnreal. 
- Same issue with the failing package export. no change there.
-  However, the blueprints cesium samples projects opens fine, i can also run and package the game with no issues.
- I have another cesium starter project that I created in the same manner as my-project. The cesium starter project I created also runs and packages with no issues.

The differerence between my-project and my starter project is that my-project is a bit more involved. It has multiple levels, some cesium based, some not.

Appreciate any further suggestions to help dive deeper, this is a big blocker for deploying this project and I will need to keep at it.

Thanks
-Will

**Comment by kring** [comment]
I'm not sure what might be causing the problem with your project. The first thing to check is that your project's C++ settings are compatible with Cesium for Unreal:
https://community.cesium.com/t/unable-to-package-ue5-0-3-project-with-cesium-v1-19-0/21162/19

If that doesn't help, then the next thing I'd look for is some sort of conflict between a third-party library used by both your project (or one of its plugins) and Cesium for Unreal. For example, if both use RapidJSON, or Async++, or anything else, but different versions of them, then things will go very poorly because in packaged builds Unreal dumps all the plugins and project source code together into one executable, and so the similar symbols in the different versions of the library will clash.

**Comment by wurrego** [comment]
Well i am not sure either, but updating to Unreal Engine 5.1.1 seemed to finally fix this issue.
