### ISSUE TITLE
 Cesium and Nanite

### ISSUE THREAD

**Issue by IndigoCloud6** [CesiumGS/cesium-unreal#1030]
when it supports  convert Cesium to nanite?

**Comment by kring** [comment]
We're interested in experimenting, but it's not currently planned. The fundamental problem is that Cesium streams meshes at runtime, whereas Nanite processing needs to happen at Editor time. It may not be practical or even possible to bridge this gap. I'm closing this because this is a question for discussion, not an actionable issue. Please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) if you would like to discuss further.
