### ISSUE TITLE
Sky problem in mobile application. Unreal 5.1.1

### ISSUE THREAD

**Issue by gggx1993** [CesiumGS/cesium-unreal#1133]
Hello friends. I ran into a problem, I can not solve it for several weeks. I searched all the forums, searched the entire Internet and could not find anything to solve this problem. When compiling the application, I have no atmosphere, just a black screen. I use version Unreal 5.1.1. Can someone help. How to solve this problem. Thank you
![Screenshot_2023-06-13-22-59-17-497](https://github.com/CesiumGS/cesium-unreal/assets/135973611/096881f6-325c-4a78-b1e7-86842598ada4)

**Comment by kring** [comment]
Is that on a mobile device of some sort? Some of the information here may help:
https://github.com/CesiumGS/cesium-unreal/issues/661

**Comment by kring** [comment]
Do you have the same problem in the Cesium for Unreal Samples project, or does it work there?

**Comment by gggx1993** [comment]
works in the project. And when I drop it on the phone it stops. What to do, can you advise?

**Comment by gggx1993** [comment]
This photo was taken on an Android device.

**Comment by COcis-io** [comment]
You can do it by hand as Kring pointed out on [661](https://github.com/CesiumGS/cesium-unreal/issues/661) but i got same black screen and i had to use different mesh and material from a iso sky temple i had around from marketplace(an SM_SkySphere mesh and an HDRI... or there is a mobile section on cesium sunsky (outliner->details) to do that automatically, but i couldn't make it work with any mesh/material... I noticed that it changes also some lights/shadow settings (another thing that im trying to make it work around all android blockers), maybe Kring can give us more information on that mobile option, because i couldn't find any info on that around my web search bubble...

**Comment by kring** [comment]
You know, I've found that the CesiumSunSky is working fine for me these days with the default settings. I'm not sure what changed. New Android device? New Unreal Engine version? A setting change? That's why I asked if the Cesium for Unreal Samples problem is exhibiting the same problem for you, because it's not for me. If that project works but yours doesn't, it should be a relatively simple matter of finding the difference in settings. So please check and let me know.

**Comment by kring** [comment]
Here's what the first level in Samples looks like on my Pixel 6 Pro, packages with UE 5.1.1:

![Screenshot_20230615-120435](https://github.com/CesiumGS/cesium-unreal/assets/924374/51fa86ce-2482-4a47-b487-4b5b2e27415f)

I chose these settings when I built it from the Platforms menu:

![image](https://github.com/CesiumGS/cesium-unreal/assets/924374/88e87b81-e40c-42be-b859-361941054128)

These is one artifact with the water material when the specular highlight is pointed directly directly at the camera, though:

![Screenshot_20230615-120446](https://github.com/CesiumGS/cesium-unreal/assets/924374/4676dbc0-6f88-4de8-9097-61c4c8586a55)

**Comment by gggx1993** [comment]
> Here's what the first level in Samples looks like on my Pixel 6 Pro, packages with UE 5.1.1:
> 
> ![Screenshot_20230615-120435](https://user-images.githubusercontent.com/924374/245972850-51fa86ce-2482-4a47-b487-4b5b2e27415f.png)
> 
> I chose these settings when I built it from the Platforms menu:
> 
> ![image](https://user-images.githubusercontent.com/924374/245973050-88e87b81-e40c-42be-b859-361941054128.png)
> 
> These is one artifact with the water material when the specular highlight is pointed directly directly at the camera, though:
> 
> ![Screenshot_20230615-120446](https://user-images.githubusercontent.com/924374/245972841-4676dbc0-6f88-4de8-9097-61c4c8586a55.png)


I tried everything as you said above! But none of this helped(
I did everything like you. Here is a photo.

![Screenshot 2023-06-15 1435023](https://github.com/CesiumGS/cesium-unreal/assets/135973611/8287144b-16d0-48b7-be30-7affe37a7a2b)

**Comment by kring** [comment]
Can you try doing the same in the Cesium for Unreal Samples project and see if it works for you there?

**Comment by gggx1993** [comment]
everything is working. thanks) but now I have no shadows, you dont know what it could be?

**Comment by kring** [comment]
How did you fix it? Just by using the Cesium for Unreal Samples? It would be helpful to know what was missing from your original project.

Shadows seem to be working for me, but they're finicky... don't appear until you get close, for example, and they sometimes disappear for unknown reasons. I'm not sure how to solve this, though. Cesium for Unreal is essentially just providing Unreal Engine with static meshes. So it might be best to raise the question in a more general UE forum. Perhaps the shadow setting defaults are different on mobile for performance reasons, or there are limitations in the mobile renderer.

**Comment by gggx1993** [comment]
I did everything as you wrote. Created a sphere and placed it in the middle. I increased it in size so that it covered my entire map. and assigned a static mesh to this sphere, and assigned the sky to this static mesh. all as you wrote)

**Comment by gggx1993** [comment]
![Screenshot](https://github.com/CesiumGS/cesium-unreal/assets/135973611/e6b72f16-aae5-4b8e-8516-2e0ac3bbe396)
