### ISSUE TITLE
Translucent blend mode and texture are ignored if baseColorFactor >= 0.996

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#1160]
This has been the case since the original implementation in #898, but I don't think there's any good reason for it.

**Comment by EvenZHAnglll** [comment]
I've encountered a problem in our project. 

We have a translucent mesh where the opacity is controlled by the alpha channel of a texture. The texture's alpha will be multiplied by the alpha value of the `baseColorFactor` , so the alpha value of the `baseColorFactor ` is set to 1 in our 3DTile data. 
However, due to the current condition in the code, this material is being set as Masked, instead of the desired translucent mode.

I believe this condition should not be used for determining the material's blend mode.

I find the codes in  **CesiumGltfComponent.cpp**.
``` C++
UMaterialInterface* pBaseMaterial =
      (is_in_blend_mode(loadResult) && pbr.baseColorFactor.size() > 3 &&
       pbr.baseColorFactor[3] < 0.996) // 1. - 1. / 256.
          ? pGltf->BaseMaterialWithTranslucency
          : pGltf->BaseMaterial;
```

I don't think the condition `pbr.baseColorFactor[3] < 0.996`  is reasonable.

**Comment by kring** [comment]
Yeah, I agree, that's why I wrote this issue. We welcome to pull request to fix it!

**Comment by EvenZHAnglll** [comment]
Do you have any suggestions for modifications? If not, I will submit a simple pull request to remove `pbr.baseColorFactor[3] < 0.996` .
