### ISSUE TITLE
Wrong .lib file name for packaging

### ISSUE THREAD

**Issue by MuttonYung** [CesiumGS/cesium-unreal#1163]
It seems that UBT expect XXXX.lib, but I have XXXX**d**.lib in the same directory instead of XXXX.lib.
For example UBT want async++.lib, while in the certain folder it's not there. But async++d.lib is.

I've built cesium-native with VS 2019, no errors or warnings. Tried to build with other ways but failed.
Is this problem happening just because of not using VS 2017?

Here is the [log file of UBT](https://pastebin.ubuntu.com/p/6FG9BxcVjc/).

![image](https://github.com/CesiumGS/cesium-unreal/assets/55025557/e217b6d8-d948-44f6-9d26-6d4abc97f654)

By the way, is there any way to test whether cesium-native is built correctly without packaging?

**Comment by kring** [comment]
The `d` suffix indicates you've built a debug build of cesium-native. If you're building a Development or Shipping version of Cesium for Unreal, you'll need to build the Release or RelWithDebInfo configuration instead. This is already mentioned in the Developer setup instructions on this page:
https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup.md

See the second-to-last bullet under "Principles". And the Windows build instructions state how to build the Release configuration:
https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup-windows.md#cmake-command-line

So I'm closing this. Please open [community forum](https://community.cesium.com/c/cesium-for-unreal/10) threads instead of GitHub issues in the future, unless you're fairly confident you're seeing a bug.

**Comment by MuttonYung** [comment]
Thank you SO MUCH. That really helps. I'll check the forum.
