### ISSUE TITLE
Cesium for Unity And ParticleSystem

### ISSUE THREAD

**Issue by XueYuQQ** [CesiumGS/cesium-unreal#1202]
The development environment is Unity2021.3.27. When CesiumForUnity is used, ParticleSystem component is added to a Cube to simulate the wake effect, adjust the position of the camera, and the particles also move with the camera. How can I solve the problem to change the position of the camera, the ParticleSystem remains stationary relative to the ground.

What happens now is that when the camera changes position, the particle system follows the Cube through height and position movements, which looks strange.

**Comment by kring** [comment]
If you're using the default Cesium for Unity camera, you'll notice there's a `CesiumOriginShift` component on it. That means that the origin of the Unity world will move as the camera moves. In order to keep an object anchored to the globe when the origin shifts, you need to add a `CesiumGlobeAnchor` component to that object. This is covered in this tutorial:
https://cesium.com/learn/unity/unity-placing-objects/

Hopefully this is possible (and works) with particles. If not, the next option is to remove the `CesiumOriginShift` component. That will be fine if your camera will stay contained to a relatively small area, but you'll see precision problems as the camera ventures far from the origin.

Please post further questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use github issues only for bug reports and feature requests.
