### ISSUE TITLE
Velocity in Z direction set to max speed after `FlyToLocationLongitudeLatitude` completes

### ISSUE THREAD

**Issue by Tijunel** [CesiumGS/cesium-unreal#1243]
Found that setting a new location with a dynamic cesium pawn would cause its velocity in the positive Z direction to be constantly set to the max speed. Using the latest UE 5.2 plugin version from the marketplace.

**Comment by Tijunel** [comment]
Note:

Changing globe anchor position via editor also causes this issue.

**Comment by j9liu** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). As noted in this [forum thread](https://community.cesium.com/t/dynamic-pawn-weird-behaviour-pulling-me-to-the-world-origin/24595), as well as [this one](https://community.cesium.com/t/camera-movement-issues-with-ue5-1-1-and-latest-cesium-plugin/23804), this happens when "Enable World Bounds Check" is true.
