### ISSUE TITLE
cesium 3d tiles cannot be seen after packing

### ISSUE THREAD

**Issue by GGGHoliday** [CesiumGS/cesium-unreal#1318]
I have successfully packaged the application with cesium3d tiles, and running the packaged application locally can see cesium3d tiles, but cesium3d tiles do not display after migrating to the server. ue5.3 cesium form ion

**Comment by kring** [comment]
We will need a lot more detail in order to help you. For example:

1. What version of Cesium for Unreal? (5.3 is the Unreal version, not the plugin version. Go to Edit -> Plugins -> Geospatial to find the plugin version)
2. What sort of tileset? Where is it being loaded from?
3. What platform?
4. Are there any messages in the log?

But this is the wrong place for such matters. GitHub issues are for confirmed bugs and concrete, actionable feature requests. Please follow up on the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead.
