### ISSUE TITLE
The flow level already has a Georeference, but GetDefault Georeference will still generate a Georeference in the main level, which should not be

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#1394]
3dtiles is placed in the flow level, and there is already a Georeference in the flow level
When using the GetDefault Georeference function, it still automatically generates a default Georeference in the main level, causing the longitude and latitude in the scene to be disordered

GetDefault Georeference (this), causing issues.

Please fix this issue. The 4.27 version is quite good

**Comment by j9liu** [comment]
Hi @kak0na,

Thanks for the report. I'm afraid that we deprecated support for UE 4.27 a while ago, and a lot of changes to the plugin are incompatible with 4.27. Still, you're welcome to build an earlier version of the plugin from source, and make fixes where needed.

With regard to your problem: if you have any Cesium objects in your main level, then it will have to generate a default georeference. So I assume that you mean, _no_ Cesium objects are in your main level, only in the sublevel, and it's still generating a extra georeference?

In any case, we entirely reworked the sublevel system in Cesium for Unreal v2.0.0, with the goal of addressing these kinds of bugs. The minimum version of UE you can use is 5.1. If you're able to upgrade to the latest version, that would be great! But otherwise, feel free to reference the changes in #1153 and incorporate them into your code.

I'm closing this issue because there's nothing we can do on our end for backwards compatibility. If you have any other questions about sublevels, feel free to post them to our [community forum](https://community.cesium.com/c/cesium-for-unreal/10). Both Cesium team members are other community members will be able to help you there!
