### ISSUE TITLE
Dynamic pawn speed control broken in UE 5.4 (at least)

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#1406]
In UE 5.4, the DynamicPawn's speed control doesn't seem to be working. It moves very slowly, and the usual mouse wheel up trick only helps a little.

I haven't tried other UE versions yet, so I'm not certain this is a UE 5.4-specific problem.

**Comment by runminyang** [comment]
eh...,i find this problem in DynamicPawn's function SpeedLineTrace,the anthor remark "If speed will increase suddenly by too much, ignore as well.. This can be an issue when 3D tiles are unloaded/loaded from scene.",i change the branch(condition is 100.0<)'s false exec link the true same. the problem is go way . not thancks me ,i am chinese handsome~,thanks anthor .
