### ISSUE TITLE
Why are there blue squares

### ISSUE THREAD

**Issue by FEJackFly** [CesiumGS/cesium-unreal#1446]
![image](https://github.com/CesiumGS/cesium-unreal/assets/24688308/4ab66866-1be1-47c2-8427-24d232818746)

**Comment by kring** [comment]
It's hard to tell what I'm looking at from just one zoomed-in screenshot. Please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) and include as much detail as you can. For example, which tilesets are you using? Where is this located? What versions of Unreal Engine and Cesium for Unreal are you using? What platform? The more information you can provide, the more likely we'll be able to help you.

I'm closing this issue because it's not a clear feature request or actionable bug report, so please follow up in the community forum instead.
