### ISSUE TITLE
There are blue squares at certain angles

### ISSUE THREAD

**Issue by FEJackFly** [CesiumGS/cesium-unreal#1452]
![image](https://github.com/CesiumGS/cesium-unreal/assets/24688308/15406187-ceba-429d-a728-216decd1509a)
UE：5.3.2
Cesium for unreal: 2.6.0

When I was in Ningbo there were blue squares at a certain Angle

29.988765
121.82024

**Comment by azrogers** [comment]
I'm afraid this is an artifact of Bing Maps, likely due to synthesizing different aerial images taken at different times from different sources. Take a look at the same spot [on Bing Maps](https://www.bing.com/maps?cp=29.993481%7E121.837371&lvl=16.4&style=h) and try zooming in and out - you'll see it switch between the terrain as it should be colored, and the blue-tinted terrain you're seeing. Unfortunately, this means that the issue is on Microsoft's end, and there's not much we can do about it. 

One "solution" to this is changing the Maximum Screen Space Error on the CesiumIonRasterOverlay component on your tileset. Raising this value will stop Cesium for Unreal from loading the higher-resolution imagery that has this blue tint - which, of course, means the imagery will be blurry up-close. An alternative is using the Sentinel-2 imagery instead of the Bing Maps imagery, which means changing the ion Asset ID on the CesiumIonRasterOverlay component from 2 to 3954. However, Sentinel-2 is a good deal lower resolution than the Bing Maps imagery, so the result is about the same.

Other than these half-solutions, you can try finding a new imagery provider and bringing it in to Cesium for Unreal. We support any imagery services that provide their data in the Web Map Service, Tile Map Service, or Web Map Tile Service formats. For example, [Esri World Imagery](https://www.arcgis.com/home/item.html?id=974d45be315c4c87b2ac32be59af9a0b) doesn't have these artifacts and supports WMTS, which means it can be used in Cesium for Unreal. However, this imagery has its own terms of use separate from Cesium and Cesium ion, which you'll need to familiarize yourself with and follow before using.
