### ISSUE TITLE
Unreal Engine And Cesium version diff

### ISSUE THREAD

**Issue by Devesh2372002** [CesiumGS/cesium-unreal#1492]
![Screenshot 2024-08-10 144005](https://github.com/user-attachments/assets/eb507b70-bff1-40aa-bfa4-310b210c0aae)
Hello,

We are currently using Unreal Engine version 5.3, but the Cesium plugin we have is only officially supported for version 5.2. Although it does run on 5.3, we are experiencing frequent crashes.

**Comment by ZhengzhongSun** [comment]
You can download plugin for UE 5.3 in [Releases](https://github.com/CesiumGS/cesium-unreal/releases).

**Comment by kring** [comment]
@Devesh2372002 that's a very surprising problem because the Epic Launcher should install the correct version of the plugin for your UE version. Perhaps you're building it from source? If that's the case, you need to change the EngineVersion field [here](https://github.com/CesiumGS/cesium-unreal/blob/v2.7.1/CesiumForUnreal.uplugin#L13) to match your UE version before you compile the plugin.

I'm closing this because I don't think there's anything actionable for us here. But please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) if you're still having trouble, and describe in more detail what you're doing that's triggering this error.
