### ISSUE TITLE
Point Input Key for Add Point (Spline Component) does not run properly when the input is a floating-point number

### ISSUE THREAD

**Issue by mincer0** [CesiumGS/cesium-unreal#1534]
I'm trying to use this node to add points to a spline, but if the --point input key-- isn't an index-like number, it doesn't run properly as shown in the picture below.

<img width="176" alt="image" src="https://github.com/user-attachments/assets/fdf36cb8-ae05-40d0-b75a-e501cd7ec496">

<img width="469" alt="image" src="https://github.com/user-attachments/assets/4150f195-889c-4b4b-9827-ddc2da2ab6d7">

**Comment by kring** [comment]
Hi @mincer0, I'm not sure I completely understand the issue. But the Spline Component is part of Unreal Engine, not something provided by Cesium. So you may need to raise the issue with Epic.

I'm going to close this because it doesn't sound like a Cesium issue, but please reopen and clarify if I've misunderstood.
