### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by hightenter** [CesiumGS/cesium-unreal#1563]
Platform: window10
UE 5.3.2

I failed to compile the latest source code.
![cmake](https://github.com/user-attachments/assets/592a43e5-8583-44d7-a1ee-116ede6e3d0d)
tip MSB806  zreo_check

**Comment by kring** [comment]
@hightenter I'm not sure what that might be. We probably need to see the full build log, not just the Visual Studio Error List view. In case it helps, the GitHub Actions script that builds for all supported platforms can be found here:
https://github.com/CesiumGS/cesium-unreal/blob/main/.github/workflows/build.yml

Please post more details to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead of creating GitHub issues. We use GitHub only for bug reports and clear feature requests.
