### ISSUE TITLE
Move ACesium3DTileset::BodyInstance property to the "Collision" category

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#246]
From @AlbanBERGERET-Epic...

It is sometimes necessary to set up custom collision behavior for Unreal Actors, including our Tileset Actors, in particular when working with the HoloLens 2. But it's currently not possible to do so without changes to the Cesium for Unreal plugin code. To solve this, we need to expose a new property on our Tileset Actors:

```
/** Physics scene information for this component, holds a single rigid body with multiple shapes. */
UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Collision, meta = (ShowOnlyInnerProperties, SkipUCSModifiedProperties))
FBodyInstance BodyInstance;
```

And then copy it to each GltfComponent that gets created. This will cause some new properties to appear on the Details panel:

![image](https://user-images.githubusercontent.com/924374/111723359-7f3c8f00-88b7-11eb-946b-b4c8822bc87a.png)

The custom "TileSets" trace response in the screenshot above was created by adding it in project settings:

![image](https://user-images.githubusercontent.com/924374/111723467-ad21d380-88b7-11eb-896c-e4accd58f35f.png)

**Comment by AlbanBERGERET-Epic** [comment]
Hi @kring,

I just tested the 1.1.0 plugin from the marketplace. Good to go, thanks a lot ! 

One concern though : You named the UPROPERTY category "Cesium|Collisions". Unfortunately, naming this particular BodyInstance property "Whatever|Collision" prevent it to be editable in the Details panel. 
This is probably something weird hardcoded in the editor. Can you please just revert it to "Collision" ? 

For my short-term demo, all is alright because the property has already been serialized in the level, but it has to be fixed to be accessible. ;-) 
 
![image](https://user-images.githubusercontent.com/59740355/115623083-b9d68480-a2c6-11eb-9bf3-48d34638baef.png)

**Comment by kring** [comment]
Thanks @AlbanBERGERET-Epic, I updated the title to reflect what still needs to be done here.
This will prevent other people from recreating your demo though, right? If so, it might be worth a quick v1.1.1 release.
