### ISSUE TITLE
GlobeAwareDefaultPawn should only overwrite ECEF from Unreal when necessary.

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#269]
Currently, `GlobeAwareDefaultPawn` uses a quick dirty way of surviving georeference changes which is to update the internal ECEF representation (`_currentEcef`) from the current Unreal position every frame in `Tick`. This is stored so that later, when the georeference changes, the recently updated `_currentEcef` can be used to calculate the new Unreal position in the new georeference. 

This is fine when this pawn is the one being controlled, since the origin will always rebase to be near the pawn and the Unreal coordinates will be small and sufficiently accurate. However, when the pawn is stationary and far away from the origin, this system more than likely causes loss in precision which in worst case will be exactly as imprecise as Unreal's single-precision (with origin rebasing). This is in contrast to the `CesiumGeoreferenceComponent` which attempts to be very careful about when to update the internal ECEF representation. 

The georeferencing of `GlobeAwareDefaultPawn` should be reworked eventually to minimize needlessly overwriting the internal ECEF representation in the cases where we can avoid it.

**Comment by javagl** [comment]
Referring to my question at https://github.com/CesiumGS/cesium-unreal/pull/459#discussion_r675639262 : Is it right that this could ~"more sensibly" be solved by overriding `ApplyWorldOffset` in the `GlobeAwareDefaultPawn`, and adding the new World offset to the current ECEF position? 

(This sounds tricky, because... the position of the pawn somehow determines whether an origin rebasing is performed in the first place, raising a load of questions about "who is going to update what based on what". But if this sounds like a viable path, I'd give it a try...)
