### ISSUE TITLE
Credits missing, duplicate Georeference, when a sub-level needs to have georeferenced objects

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#273]
Normally, georeferenced objects are put in the PersistentLevel, while local, non-georeferenced objects are placed in sub-levels. But it can sometimes be useful to put georeferenced objects in a sub-level too, so that they're shown/hidden with the sub-level. But when we do that, it doesn't appear to be possible to reference the Georeference or CreditSystem actors in the PersistentLevel, so we end up creating new ones within the sub-level.

This is less than ideal for the Georeference because it usually means we have to make sure they stay in sync, and it's a little weird to have two things doing origin rebasing. But it's more of an immediate problem for the CreditSystem because the UI only attaches to one CreditSystem, meaning some of the credits are not shown.

We should see if there's a way to find/use/reference PersistentLevel objects from sub-levels. And, if not, then the UI should at least be smarter about where it obtains credits.

**Comment by javagl** [comment]
I stumbled over this issue in the context of tests for the Georeference refactoring. Since I'm not sure about some workflows related to creating/editing sublevels in general, I'll drop some observations here:

The original problem described here might have been related to the original [`GetDefaultForActor`](https://github.com/CesiumGS/cesium-unreal/blob/670cbe9e922290d41608a8160e6a8387bc87fb3d/Source/CesiumRuntime/Private/CesiumGeoreference.cpp#L35) implementation. This implementation looked for a Georeference in the same level as the actor. The current state of [`GetDefaultGeoreference`](https://github.com/CesiumGS/cesium-unreal/blob/bp-function-library-initializations/Source/CesiumRuntime/Private/CesiumGeoreference.cpp#L41) searches in the *world*. 

From a usage perspective, this may cause an issue. 

When opening a Persistent Level with sublevels, and "activating" a sublevel by double-clicking it in the "Levels" panel, it is possible to add a tileset to this sublevel: 

![CesiumUnreal Sublevel Georef 01](https://user-images.githubusercontent.com/5597569/124659817-a68a8c80-dea5-11eb-821d-3ebebbe53004.png)

This tileset will pick up the global default Georeference, as desired (?).

**But**... this state cannot be saved. It generates a message

> EditorErrors: Warning: Can't save ../../../../../../Develop/CesiumUnreal/cesium-unreal-samples/Content/SublevelTest/Sublevels/TestSublevel01.umap: Graph is linked to object CesiumGeoreference /Game/SublevelTest/SublevelTest.SublevelTest:PersistentLevel.CesiumGeoreferenceDefault (Georeference) in external map

In contrast to that: When opening the sublevel directly, from the content browser, and adding an asset there, it will generate a new Georeference. This level can be saved. When opening the Persistent Level afterwards, and "activating" the sublevel, then the Georeference and CreditSystem appear twice:

![CesiumUnreal Sublevel Georef 02](https://user-images.githubusercontent.com/5597569/124659945-d6399480-dea5-11eb-96a4-39b39c4d4caa.png)

To quote from https://github.com/CesiumGS/cesium-unreal/issues/330#issuecomment-862579740 :  

> The conceptual difference between a World and a Level in UE4 is not something I'm exactly clear on. 

Same here. The exact semantics of "loading" a sublevel, and how it's connected to the world or the persistent level, are not entirely clear for me either. (Roughly: What exactly happens when double-clicking a sublevel in the "Levels" window?).

I'm not sure where the Georef+CreditSystem should be. My impression is that, since Sublevels are supposed to be edited in a "standalone" fashion, by opening them from the Content Browser, they essentially _cannot_ refer to anything in the Persistent Level. 

> If putting a second georeference in the sublevel becomes a semi-permanent concept, we should probably just make a SubLevelGeoreference class that can't origin rebase, can't do any of the sublevels stuff, and has a georeference that's fixed to the sublevel and can't be changed (so that it is guaranteed to stay in sync).

**Iff** this turns out to be a promising path, then I'd prefer to remove the sublevel handling from the Georeference now, during the refactoring. Despite (or maybe because of) the efforts that already went into the refactoring, I'd like to avoid having to do this in a (probably compatibility-breaking) "Refactoring 2.0" in the near future.

**Comment by kring** [comment]
These days, Tilesets in sublevels will automatically pick up the persistent level's georeference, and this will no longer prevent us from saving the level. However, if we open the level independently, that will still trigger creation of a Georeference inside that particular level, and that will still break things. The best solution at the moment is "don't do that." When using sub-levels with Cesium, only edit that as sublevels, never as independent levels.

**Comment by j9liu** [comment]
@kring Has #1153 affected the state of this issue at all?

**Comment by kring** [comment]
No, I don't think it has.
