### ISSUE TITLE
Possible issue with packaging Unreal projects

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#299]
Received a report of an unknown error when trying to package a game with a Cesium map inside of it. Awaiting more information on this issue.

**Comment by timFinn** [comment]
Running into this issue after adding a Cesium map to the project. Set up according to procedure found in Cesium For Unreal documentation.

Docs said to drop the release into the Project plugins. Should this be copied into the Engine plugin folder?

**Comment by kring** [comment]
@timFinn yes, a built version of the Cesium for Unreal plugin should generally be added as an engine plugin, not to the project's Plugins directory. However, you should also be able to clone the plugin into the project's Plugins directory and follow the work-in-progress) guide to set up the development environment.

I can't quite tell from your log, but it's also possible you're running into #245.

I'm going to close this because I don't think there's currently much actionable. If you're still running into problems, it's probably best to raise in the community forum: https://community.cesium.com/c/cesium-for-unreal/10.
