### ISSUE TITLE
loading local GLTF data at runtime

### ISSUE THREAD

**Issue by preetishkakkar** [CesiumGS/cesium-unreal#301]
Hello, thanks for the wonderful work! 

I have a bit of volumetric data saved as GLTF files along with JSON file i.e. x,y,lod to the corresponding GLTF File, I would like to load them on runtime directly from disk. I have handwritten logic that can tell me which GLTF files to load based upon location. Can someone help me how I can integrate it with FloatingPawn location & fetch & show GLTF files on runtime. At this moment, I am mostly interested in loading these files at runtime. Would appreciate if someone can help.

**Comment by kring** [comment]
@preetishkakkar It might make sense to convert your data to [3D Tiles](https://github.com/CesiumGS/3d-tiles) rather than using your custom LOD format.

Cesium for Unreal currently does not allow glTFs to be loaded independently of 3D Tiles, but it would be relative easy to add. I wrote #390 to cover that. I'm going to close this issue, and I'd suggest taking it to the [Community Forum](https://community.cesium.com/c/cesium-for-unreal/10) if you're interested in discussing the use of 3D Tiles for your use-case.
