### ISSUE TITLE
Support the CESIUM_RTC glTF extension

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#310]
Although the [glTF CESIUM_RTC extension](https://github.com/KhronosGroup/glTF/tree/master/extensions/1.0/Vendor/CESIUM_RTC) was originally designed for glTF 1.0, there apparently are 3D Tiles assets with B3DMs that use this extension even though their glTF are **2.0**. The decision of whether this extension should be supported in theses cases has implicitly been made - probably for backward compatibility (and maybe compatibility with CesiumJS). 

However, the `RTC_CENTER` value is currently looked up in the `extras` dictionary of the model, via https://github.com/CesiumGS/cesium-unreal/blob/712c0b4221f9d0bf3535ad30563700c9d597bbf7/Source/CesiumRuntime/Private/CesiumGltfComponent.cpp#L1144 , although it should be contained in the `extensions` dictionary. 

The `extensions` dictionary is currently not considered by the CesiumGltfReader, but extended support for glTF extensions is currently addressed in the https://github.com/CesiumGS/cesium-native/blob/gltf-extensions branch. When this is merged, the aforementioned place in `CesiumGltfComponent` should be updated to pick the `RTC_CENTER` from the `extensions` dictionary.

**Comment by kring** [comment]
CC CesiumGS/cesium-native#195

**Comment by javagl** [comment]
Sorry, I misunderstood the statement in the linked issue, even though it was as clear as it could be:

> Currently when we find an `RTC_CENTER` property in a b3dm, we communicate that to the rendering engine by adding an `RTC_CENTER` property to the glTF's `extras`. 

It explicitly refers to the `RTC_CENTER` that can be found in [the Feature Table of a B3DM](https://github.com/CesiumGS/3d-tiles/blob/master/specification/TileFormats/Batched3DModel/README.md#global-semantics). 

Using the `extras` as a vehicle for transporting such information raises questions. First of all: It is mutating the model, it is not transparent, and not obvious, and **if** this is done, it should be explicitly documented, at the point where it is used:

    // We put the RTC_CENTER from the B3DM into the "extras" in Batched3DModelContent.cpp,
    // so check whether it was present:
    auto rtcCenterIt = model.extras.find("RTC_CENTER"); 

But beyond that, it raises the question of how to handle cases where the `RTC_CENTER` is contained in the B3DM **and** in the glTF. If both should be supported, we'd end up with

    auto rtcCenterItA = model.extras.find("RTC_CENTER"); 
    auto rtcCenterItB = model.extensions.find("RTC_CENTER"); 
    if (bothAreThere(rtcCenterItA, rtcCenterItB)) { println("Help!"); }

and no way of sensibly resolving that. The same would be the case (only "earlier") if we transported the `RTC_CENTER` from the B3DM via the `extensions` (and not the `extras`). (In that case, we would have to additionally declare that as `extensionsUsed` for consistency, even though it was never intended for glTF 2.0...)

---

Many abstraction levels higher, this is related to https://github.com/CesiumGS/cesium-native/issues/71 . Right now we're sending a `CesiumGltf::Model` to Unreal. In the future, this might have to include information about the feature/batch table (which would then cover the `RTC_CENTER` implicitly).

**Comment by kring** [comment]
In 3D Tiles Next, b3dm and similar go away and it's all glTF. Batch and feature tables are attached to glTFs via extensions. When Cesium for Unreal loads a (legacy) b3dm, it should upgrade it by creating the corresponding glTF extension(s). At least, that's my current thinking.

Specifying (different) RTC_CENTER both in the b3dm and in the glTF is nonsensical. We should warn and pick one to have priority. Ideally the one with priority should be documented.

If we still need RTC_CENTER for 3D Tiles, then in 3D Tiles Next we'll need a glTF 2.0-compatible extension to add it. At which point we'll use that. Until then (or if we decide we don't need it at all anymore, it's just legacy nonsense), we can continue to use extras, or we can use the glTF 1.0 one, since it works fine other than it's technically written against the wrong glTF version. Or we can automatically include the extra translation in the node transform(s) (not sure offhand what is involved in this).

**Comment by dreamhappy** [comment]
Which version will solve this problem?

**Comment by kring** [comment]
It is not currently targeted toward a particular release. We recommend upgrading your tilesets to be spec-compliant if at all possible.
