### ISSUE TITLE
Cannot package blueprint-only projects with this plugin in the local project folder

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#312]
Unreal Engine is particular about packaging projects. I did some testing after [this pull request was submitted on cesium-unreal-samples](https://github.com/CesiumGS/cesium-unreal-samples/pull/3) and found the following results with a small test project and C++ plugin:

:white_check_mark: Blueprint project with engine-installed plugin (also tested with cesium for unreal marketplace version + cesium unreal samples)
:white_check_mark: C++ project with engine or local plugin
:x: Blueprint project with local plugin (both source and pre-built versions of the plugin). Gives the following error: `Plugin XX failed to load because module XX could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.`

Seems like blueprint-only projects with locally-installed C++ plugins must be converted to C++ projects to package successfully. Since the [cesium-unreal-samples](https://github.com/CesiumGS/cesium-unreal-samples) is currently Blueprint-only and should preferably stay Blueprint-only for ease of distribution, I propose creating a separate UE4 C++ project for the purposes of developing, building, and testing the `cesium-unreal` plugin in-editor and in packaged builds.

**Comment by kring** [comment]
Rather than maintaining a separate project, perhaps we just include in the developer guide a note about adding a C++ file to cesium-unreal-samples to convert it to a C++ project? @javagl could you work it into #384?

**Comment by javagl** [comment]
I'm not entirely sure about 

- the current state of the PR at https://github.com/CesiumGS/cesium-unreal-samples/pull/3 (my understanding of *"should preferably stay Blueprint-only"* is that it will likely *not* be merged)
- whether *this* issue is in any way related to that PR (my understanding is that it is *not* (directly) related)

But I'd hesitate adding instructions for "adding some C++ file" in the developer setup. One reason is that it will make the process more complicated than it needs to be (particularly for someone who doesn't want to package the result it all). Another ("non-technical") reason is that I don't understand what's going on there in the "Unreal Build Magic Blackbox", and why this is necessary in the first place. I'd feel a bit uncomfortable to say "Click here, do that, rinse and repeat, it doesn't work otherwise and we don't know why".

(If this could be fleshed out, *for example* (!), leading to two sections like "Setup for dev-only", and "Setup for packaging", then this *could* be OK, but in all cases, I'll have to read more about packaging and the Unreal Build Magic first...)

**Comment by kring** [comment]
> my understanding of "should preferably stay Blueprint-only" is that it will likely not be merged

Right, we don't want the samples to be a C++ project because it will make things harder for our users only to make our lives slightly easier.

> If this could be fleshed out, for example (!), leading to two sections like "Setup for dev-only", and "Setup for packaging", then this could be OK, but in all cases, I'll have to read more about packaging and the Unreal Build Magic first...)

I think it would be fine to add a bit to the developer notes at the end that says "if you need to be able to package, you'll need to make it into a C++ project first, here's how." If you want to dig more into _why_, I'm certainly not opposed. I don't completely understand it myself.

**Comment by kring** [comment]
We have instructions now for converting a Blueprint project to a C++ project:
https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/developer-setup-windows.md#converting-the-project-into-a-c-project

I think this can be closed.
