### ISSUE TITLE
Changing Screen Space Error of CWT causes strange collision issue

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#313]
This is a bug that was originally noticed when trying to place foliage on Cesium World Terrain. 

When lowering the Screen Space Error of Cesium World Terrain, it seems like something gets dirty in the scene and a new collider is overlaid over the existing collider. My best guess is that it's the lowest-resolution CWT, glitched out and existing in the level. This seems to be an editor-only issue, as the floatingpawn does not collide with this collider in play, and re-opening the scene fixes it. The only situation where it seems to cause problems is when trying to drag things into the viewport, or placing foliage. 

You can visualize the issue by using the "Player collision" view mode. (Note that, for some reason, changing the SSE while Player Collision view is on causes the issue to not happen.) 
Prior to changing SSE:
![CWT_PreSSE](https://user-images.githubusercontent.com/39537389/113787289-be1c7280-9708-11eb-9f80-9750df199922.PNG)

After changing SSE:
![CWT_PostSSE](https://user-images.githubusercontent.com/39537389/113787307-c96f9e00-9708-11eb-8ff9-926eaebbaa98.PNG)

### Steps to reproduce:
1. Create a new blank level
2. Add Cesium World Terrain
3. Add a SunSky (Optional, if you don't it will just be dark but you don't need to see)
4. Make sure view mode is Lit or Unlit
5. Change the Maximum Screen Space Error of the CWT from 16 to 8
6. Change view mode to Player Collision, or try to place foliage
7. See issue

**Comment by kring** [comment]
I can reproduce this, but despite lots of digging I have no idea what's going on yet.

The weird extra collision shapes are indeed a tile. In the default view in Denver, the tile responsible for the extra shapes is terrain tile L8-X106-Y184. In the Player Collision or Visibility Collision view, you can even click on it and its URL will be written to the console.

In the steps I'm using to reproduce this bug, this tile is never actually rendered. It's loaded because it's an ancestor that might be needed in the future to avoid holes, but we never set it visible. Collision starts off enabled, but we turn it off immediately after we construct it.

The problem seems to be triggered by `OnConstruction` being called, or perhaps by some other process that is also triggered by editing a property. You can trigger the bug by editing _any_ property of the tileset, not just the Max SSE. For example, I toggled Replication -> Net Load on Client (which AFAIK shouldn't do anything!), and that triggered the bug, too.

I recently added some code to set all tiles to "not visible, no physics" in OnConstruction, so at first I thought that could be the culprit somehow. But commenting-out that code doesn't change anything.

The only lead I have at the moment is this bit of code in the engine:
![image](https://user-images.githubusercontent.com/924374/116511605-06930e80-a90a-11eb-93b0-6f1b8691945b.png)

It gets executed when we initially disable collision for the tile after constructing it, and it appears to enable query-only collision at the world's request even though we're trying to disable it. Which sounds slightly suspicious, but definitely isn't a complete explanation because after executing this code the Player Collision view does _not_ show the tile. Not until we change a property and/or trigger OnConstruction.
