### ISSUE TITLE
Provide more detailed information when OAuth2 token exchange fails

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#314]
When `Connection::completeTokenExchange` fails, the user will be shown a message like this:

```
Not authorized! Please close this window and return to Cesium for Unreal
```

Which is not terribly helpful when the user pressed Allow but something else went wrong. We should include more details of what went wrong.

**Comment by kring** [comment]
This would help diagnose problems like this:
https://community.cesium.com/t/error-connecting-cesium-to-unreal/12953/3

**Comment by javagl** [comment]
I could take a look at that. The "more details" should probably include the `clientID` and `scopes`, and the `exception.what()` message (assuming that this can never contain critical information in any form). 

Anyhing else that could be useful there?

Should there also be some guiding text like 
> "Please verify that you are logged in to Cesium ion. If the problem persists, send the error information to `some mail address`"

(or point them to the forum or so)?

**Comment by kring** [comment]
That all sounds good to me @javagl. I don't think it's necessary/helpful to add "Please verify that you are logged in to Cesium ion" because they should be forced to log in before they can get to this point. Telling them to contact support if something goes wrong is a good idea, though.

**Comment by javagl** [comment]
I addressed this in https://github.com/CesiumGS/cesium-native/pull/214 (it's only `cesium-native`, actually).

While reading the related code, I noticed some redundancy and duplication, and cleaned this up a little.

During testing, I noticed that pressing "Deny" in the browser window caused an "Invalid state" to be reported, although there is more sensible error information given:

![CesiumUnreal Connection Example](https://user-images.githubusercontent.com/5597569/115077925-20daee80-9eff-11eb-91f2-bca99876d20c.png)

(Yeah, one comment said `// TODO: nicer HTML`, and we can argue about whether *that* goal has been achieved here, but... I hope it's OK...)

In order to sensibly test this ... I'd need an error. One could probably set up some fake server for that, but to do a *basic* test, I just intentionally threw one of the possible exceptions, and the result will be something like this:


![CesiumUnreal Connection Example 2](https://user-images.githubusercontent.com/5597569/115078164-7dd6a480-9eff-11eb-95b3-28154e9b66c9.png)

**Comment by kring** [comment]
Fixed in CesiumGS/cesium-native#214

**Comment by yongxinyuan** [comment]
my unreal editor is broken when i compile a custom Actor, after this, my connection always faild,  `URL: https://api.cesium.com/oauth/token` is faild, all dns trying is timeout, i guess maybe something is lost when editor is broken.

**Comment by kring** [comment]
@yongxinyuan you've posted a comment to an old, closed issue. Please instead post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) and include as much detail as you can about what is going wrong so that we can try to help you out.
