### ISSUE TITLE
Allow Cesium 3D tileset materials to be set to Material Instances as well as materials

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#317]
The "Material" parameter in the Cesium/Rendering category of a Cesium3DTileset currently only accepts base materials. Material instances are an important part of efficient material design in Unreal. This parameter should be updated to accept instanced materials as well.

**Comment by xuelongmu** [comment]
Changing the parameter type from `UMaterial` to `UMaterialInterface` should let you use Material Instances and base Materials. I started taking a crack at this, and discovered that there were a bunch of other functions/classes that contain `UMaterial` references, that will also have to be changed. Before I continue, @kring are there any reasons I might be missing on why `UMaterial` is being used instead of `UMaterialInterface`?

**Comment by xuelongmu** [comment]
I went ahead and made the changes. Let me know if this works for you @argallegos
