### ISSUE TITLE
Customize material used to render tilesets

### ISSUE THREAD

**Issue by getinthedamnbox** [CesiumGS/cesium-unreal#331]
How can I access the material used by Cesium for Unreal to render tileset data? Can I feed it a custom texture and/or a custom algorithm?

A couple of example use cases would be:

1. I have a tileset of some terrain, and I want to be able to switch between its default photorealistic texture and a different one at runtime.
2. I have a tileset of some terrain, and I want to apply custom shading logic (e.g., elevation shader).

**Comment by nithinp7** [comment]
@getinthedamnbox The materials used for tilesets can be found in the `/Plugins/cesium-unreal/Content/` folder. For instance, terrain tilesets with raster overlays use the `GltfMaterialWithOverlays`. It's possible to blend in custom textures, apply normal maps, etc. by editing those. Once we have a coherent idea of what sort of material customizability would be useful, we can likely parameterize and automate this process a bit better (right now it feels a bit hard-coded and rigid). 

We can also add more specific parent materials that get instantiated in certain situations (e.g., displacement maps, clipping planes shader). The decision of which parent material to instance from gets made on a per-gltf-primitive basis, we could easily put an interface there to allow for custom decision-making on what material to instance from in what case.

CC: @argallegos Alex has been doing some cool experimentation with the material system and we've been talking about some relevant material-related stuff here:  https://github.com/CesiumGS/cesium-unreal/issues/322

**Comment by argallegos** [comment]
Yep, this is relatively straightforward to do as long as you don't mind getting into the Material Editor a little bit, and for specific common use cases (like elevation shaders, topology lines, etc) we will probably want to look into creating a library of those materials so we can reuse and modify them easily.

Currently if you want to play around with making new materials, I recommend duplicating the `GltfMaterialWithOverlays` as well as the `RasterOverlay`. You'll do most of your work in the `RasterOverlay`, but you need to change the RasterOverlay nodes in the GltfMaterial to your modified one in order to use your new material.

**Comment by getinthedamnbox** [comment]
Got it, thanks @nithinp7 and @argallegos! I'll start working with those materials and will figure out what would be helpful to parameterize.

**Comment by kring** [comment]
I'm closing this because I don't think there's any particular action remaining.
