### ISSUE TITLE
Moving the pawn and another georeferenced actor in the same tick causes problems

### ISSUE THREAD

**Issue by getinthedamnbox** [CesiumGS/cesium-unreal#422]
I have an Unreal application written in C++ (not Blueprints) using Cesium for Unreal. When my application starts, it moves the player pawn to an ECEF location (plus an offset). It also spawns a non-player actor (which has a `CesiumGeoreferenceComponent`) and moves it to that same ECEF location. If these two steps happen on different ticks, everything works fine. But if they happen in the same tick, the non-player actor's location doesn't stay properly rooted to the spot on Cesium World Terrain.

The non-player actor is often (but not always) initially moved to the correct location on CWT, but then when I move the player pawn, the non-player actor moves in the wrong direction. It seems to be attempting to move with the tileset as the world's origin is rebased, but the actor's frame of reference has been rotated incorrectly. This also happens if I move the actor to an ECEF location and then immediately rotate it with `SetActorRotation`.

I need to be able to support pawns that derive from `AGlobeAwareDefaultPawn` as well as pawns that don't derive from it but have a `CesiumGeoreferenceComponent`. I move the globe-aware pawn with `AGlobeAwareDefaultPawn::SetECEFCameraLocation()`, and I move the globe-unaware pawn with `UCesiumGeoreferenceComponent::MoveToECEF()`. I move the non-player actor with `UCesiumGeoreferenceComponent::MoveToECEF()`, too.

As a side note, after I move the globe-unaware pawn, I have to force the Georeference to update immediately after, or else the orientation of the world ends up wrong. I do it like this:

```
glm::dvec3 lonLatHeight = georeference->TransformEcefToLongitudeLatitudeHeight(averageEcef);
georeference->SetGeoreferenceOrigin(lonLatHeight);
```

I'm assuming the problem with moving both actors in the same tick occurs because the world origin is rebased in `Tick()`, after it checks the distance between the camera and the origin. If I don't wait for that tick before moving other actors, I get the bug.

I don't understand the problem well enough to fix it, but I was able to work around it for now.

cc #330

**Comment by xuelongmu** [comment]
Random guess, but could you try changing `SetNewWorldOrigin` in `CesiumGeoreference.cpp` to `RequestNewWorldOrigin`? There are two calls to change. I have made this change in a branch I'm working on but haven't gotten a chance to test it.

**Comment by getinthedamnbox** [comment]
> Random guess, but could you try changing SetNewWorldOrigin in CesiumGeoreference.cpp to RequestNewWorldOrigin?

Thanks, after making this change, I'm no longer seeing the behavior where the non-player actor moves in the wrong direction when the world origin is rebased. The actor is being spawned in the wrong location, though---off by just a few hundred meters.

If I'm reading it right, `RequestNewWorldOrigin()` tells the application to update the world origin on the next tick, as opposed to `SetNewWorldOrigin()`, which does it immediately. Could it be that if I spawn an actor at an ECEF on the other side of the world before the world origin is changed, floating-point error puts it slightly off from where it's intended to be?

**Comment by javagl** [comment]
I'm currently investigating an issue that is _probably_ strongly related to that, in the context of the Georeference refactoring. 

Before the refactoring, there had been some special treatment for the the order in which "tick" functions are executed, around https://github.com/CesiumGS/cesium-unreal/blob/761984a9db82c84526d99b27d26f17c31cd8ccae/Source/CesiumRuntime/Private/CesiumGeoreference.cpp#L246 ,  but this has been removed when the `ICesiumGeoreferenceable` interface was removed.

**Very** handwavingly: It might be a bit problematic to do a "hard" call to `SetNewWorldOrigin` in the Georefrence (compared to the `Request...` call), because then, the actual rebasing might take place when *some* actors already ticked, and some others didn't. (I *assume* that the `Request` will cause the rebasing to happen either *before* or *after* all actor ticks in the next pass). 

Investigating this further...

**Comment by kring** [comment]
Closing due to lack of update, which hopefully means it isn't happening anymore. A lot has changed in this code since this issue was written. Please reopen if you see this again, though.
