### ISSUE TITLE
SQLite Issue

### ISSUE THREAD

**Issue by Tijunel** [CesiumGS/cesium-unreal#447]
![image](https://user-images.githubusercontent.com/35385306/119069571-983eea80-b9a3-11eb-8c01-a1ce280e1d7f.png)
Cesium3DTileset.cpp

This throws an exception when running a shipping build of the game. There are no further details from VS besides 'Exception was thrown'. 

I noticed that there is a separate issue regarding UE's SQLite Plugin, my guess is resolving it will fix this issue. When I turned off the plugin, it fixed the issue. Would be nice to have UE's SQLite integrated as it is required for various other plugins such as Quixel. 

Small inconvenience, otherwise, awesome job! This is some truly incredible technology - much appreciated.

**Comment by kring** [comment]
@Tijunel you may be able to work around this problem by deleting Cesium for Unreal's cache DB before running the shipping build. On Windows, it can be found here:
`%userprofile%\AppData\Local\UnrealEngine\4.26\cesium-request-cache.sqlite`

(%userprofile% will be something like `C:\Users\kring`)

We're working on a proper fix for this, but with the version of SQLite in UE being nerfed and yet sharing all the same symbol names as a "real" version (so the Cesium for Unreal plugin ends up linking against it unwittingly in Shipping builds), it's quite challenging.

I'm going to close this because I don't think there's any action separate from #245.
