### ISSUE TITLE
SkyAtmosphere sometimes hides earth's surface

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#527]
This was originally spotted by a user on the forum - https://community.cesium.com/t/resolved-issue-with-cesium-sun-sky-hiding-earth-surface/13743

The SkyAtmosphere of CesiumSunSky will occasionally hide earth's surface when viewing from space. 
![atmosphereIssue](https://user-images.githubusercontent.com/39537389/123982757-4c636600-d991-11eb-8059-238ca1a7614c.gif)

This even persists on the ground if you zoom into an affected area - the imagery layer fades to black.
![atmosphereIssueGroundShort](https://user-images.githubusercontent.com/39537389/123983810-268a9100-d992-11eb-8387-732725755fa3.gif)

From my testing, it looks like this depends on proximity to the georeference.

When the sun is not lighting the area where the georeference is, the terrain imagery will fade to black, even if it's light in the area where the camera currently is. We've noticed that lighting is funky the farther you get from the Georeference, but I don't think we've noticed this specific issue before. 
![image](https://user-images.githubusercontent.com/39537389/123985178-4078a380-d993-11eb-861f-8ac3d862992a.png)
(Looks pretty cool, though.)

Since we encourage users to use world origin rebasing if they are traveling far from the original georeference, I don't think that it's really a breaking issue for projects on the ground. However, it's definitely undesirable when viewing the earth from space. 

The forum user noted that changing the Transmittance Minimum Angle in the SkyAtmosphere component of CesiumSunSky from -90 to 90 degrees fixes the issue. The Sky Atmosphere documentation describes the Transmittance Minimum Angle as "The minimum elevation angle in degrees that should be used to evaluate the sun transmittance to the ground. Useful to maintain a visible sun light and show on meshes even when the sun has started going below the horizon. This does not affect the aerial perspective." 
Setting it to 90 essentially means that the sun transmittance is always evaluated. This may be desirable, but could also come with performance or graphical problems. It's also concerning that the parameter does seem to affect the aerial perspective, there may be a bug. 

We should do more testing to make sure there are no side effects, but if there are not and we have no better solution, we should change the Transmittance Minimum Angle of the SkyAtmosphere of CesiumSunSky to 90 in the plugin.

@xuelongmu is this still a problem in your branch with the recent changes to CesiumSunSky?

**Comment by xuelongmu** [comment]
I think I've been having the same issue in an internal project - when flying from the US to sand dunes in Namibia, I see that the sun is in the sky, but the dunes are still in shadow. After messing with the solar time a little bit, I'm able to get the dunes lit properly, but it seems to only work within a certain range of times.

I don't completely understand the Transmittance Angle concept (maybe a crude diagram would be helpful) but I would imagine that Unreal is having a tough time computing accurate transmittance angles when a) traversing halfway across the globe, and b) not using sublevels, as orientation and gravity become way off at that point.

**Comment by kring** [comment]
I've been running with `Transmittance Minimum Angle` set to 90 degrees, because with the default (-90), the sun lighting really just doesn't work reliably when far from the georeference origin. But there are different problems...

When set to -90, the Paris sub-level looks like this:
<img width="609" alt="image" src="https://github.com/CesiumGS/cesium-unreal/assets/924374/fca2da83-8db8-4a2b-bbdb-5b8c886f72f3">

Set it to 90, and that nice sunrise (sunset?) shading goes away:
<img width="608" alt="image" src="https://github.com/CesiumGS/cesium-unreal/assets/924374/7551e2cc-b2de-4b72-bbb9-8e4ced7e2eea">

We can get the nice shading back by enabling the `Per Pixel Atmosphere Transmittance` property on the DirectionalLight. In fact it looks identical to when `Transmittance Minimum Angle` is set to the default value.

But with that enabled, the planet looks dark from space. And there are these wacky artifacts when transitioning from (dark) space views to (light) surface views.
<img width="934" alt="image" src="https://github.com/CesiumGS/cesium-unreal/assets/924374/f62c7a0d-9835-4ff9-80fa-35d316937e9f">

![transmittance](https://github.com/CesiumGS/cesium-unreal/assets/924374/0d6057cb-5fba-4552-bc46-d62fdf476f1d)
