### ISSUE TITLE
Water effect "pops" when origin rebasing

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#534]
Every time the origin is rebased, the water effect snaps slightly to a new location.

**Comment by nithinp7** [comment]
The water texture uses an `Absolute World Position` node in the material (instead of the regular uv coords) to sample the noise, this lets adjacent tiles have seamless waves without the boundary artifacts that would appear if typical uv coords were used. Although the node is called "Absolute" World Position, I'm pretty sure it does not take origin rebasing into account. 

It may be worth a try to add an `ApplyWorldOffset` override in `CesiumGltfComponent` that can update some world origin parameter on the materials. It doesn't appear that there exists an Unreal-provided way to get the world origin in the shader. If we can put together the world origin and world position in the shader, we can perhaps get a consistent noise sampling for the waves across origin rebasing. It still won't be consistent across changes to the _georeference_ origin of course, but that may be stating the obvious.

**Comment by kring** [comment]
Not an issue in UE5 because there's no more rebasing, and we're unlikely to address it just for UE4. Closing.
