### ISSUE TITLE
How to add cloud and stars like Unreal Engine‘s BP Sky Sphere

### ISSUE THREAD

**Issue by xingrui94** [CesiumGS/cesium-unreal#540]
The CesiumSunSky cannot add clouds and stars, is there a method to add cloud and stars like Unreal Engine‘s BP Sky Sphere below:

![image](https://user-images.githubusercontent.com/29156275/124428018-bff4e100-dd9e-11eb-9ca4-20cb2dc732f6.png)
![image](https://user-images.githubusercontent.com/29156275/124428126-dc911900-dd9e-11eb-9bfe-61a0f42e6216.png)

**Comment by kring** [comment]
@xingrui94 the CesiumSunSky is provided as a convenience. You're welcome to use the regular UE SkySphere if you prefer it. Or perhaps volumetric clouds: https://docs.unrealengine.com/4.26/en-US/BuildingWorlds/LightingAndShadows/VolumetricClouds/

I'm closing this because I don't think there's much to do specifically in Cesium for Unreal. If you want to discuss further, please consider posting to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).
