### ISSUE TITLE
Packaging fails if Blueprint Nativization Method = Inclusive

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#549]
This was brought up by a [user on the forum](https://community.cesium.com/t/packaging-fails-if-blueprint-nativization-method-inclusive/14390). 

It seems like nativizing blueprints does work with Cesium for Unreal, and will cause packaging to fail. According to Lildreas on the forum, this is something we should support, as it can improve performance of packaged builds and is especially important for XR applications. 

Lildreas also provided additional info on blueprint nativization - https://docs.unrealengine.com/4.26/en-US/ProgrammingAndScripting/Blueprints/TechnicalGuide/NativizingBlueprints/

The error log provided in the forum post is:
```
UATHelper: Packaging (Windows (64-bit)): Building 8 actions with 20 processes…
UATHelper: Packaging (Windows (64-bit)): [1/8] Default.rc2
UATHelper: Packaging (Windows (64-bit)): [2/8] SharedPCH.Core.cpp
UATHelper: Packaging (Windows (64-bit)): [3/8] CesiumForUnrealSamples.cpp
UATHelper: Packaging (Windows (64-bit)): [4/8] SharedPCH.Engine.cpp
UATHelper: Packaging (Windows (64-bit)): [5/8] Module.NativizedAssets.gen.cpp
UATHelper: Packaging (Windows (64-bit)): The contents of are available only with C++17 or later.
UATHelper: Packaging (Windows (64-bit)): C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGeospatial/Ellipsoid.h(102): error C2039: ‘optional’: is not a member of ‘std’
UATHelper: Packaging (Windows (64-bit)): C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\INCLUDE\cmath(714): note: see declaration of ‘std’
UATHelper: Packaging (Windows (64-bit)): C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGeospatial/Ellipsoid.h(102): error C2143: syntax error: missing ‘;’ before ‘<’
UATHelper: Packaging (Windows (64-bit)): C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGeospatial/Ellipsoid.h(102): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
UATHelper: Packaging (Windows (64-bit)): C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGeospatial/Ellipsoid.h(103): error C2238: unexpected token(s) preceding ‘;’
```

@kring previously suggested adding `CppStandard = CppStandardVersion.Cpp17;` to the project's build.cs, but that did not seem to solve the issue.

**Comment by Lildreas** [comment]
Hi,
any update on this?
Best
Andreas

**Comment by Lildreas** [comment]
Hi guys,

found a way around this issue.

First I tested if this is a problem with my Unreal and VS installation, I completely removed UE 4.27.1 and Visual Studio 2019 Pro from my machine and cleaned all files from VS from everywhere.

Then I downloaded 4.27.1 and VS 2019 Pro again and did a clean install. But the issue persisted.

The only solution that worked for me was to change the Unreal Build Tool and hardcode it to use C++17 standard, because adding this in the projects build.cs (using "CppStandard = CppStandardVersion.Cpp17;") alone did not work.

a) ChangeUnreal Build Tool in VS 2019

Open the project file "UE_4.27\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.csproj".
Open the file "Platform\Windows\VCToolChain.cs" in the Solution.
Search for the method "AppendCLArguments_Global" and add this line at the end (for me it was line 574):

Arguments.Add("/std:c++17");

Now do a Build of the solution, a new UnrealBuildTool.exe will be created.

b) Open Unreal and your project

Open the projects build.cs and add the Cpp17, couldn't hurt (don't know if it's needed though):

public **YourProject**(ReadOnlyTargetRules Target) : base(Target)
{
       	CppStandard = CppStandardVersion.Cpp17;
	...
}

And then build and package your game and use nativize Blueprints, and it works now, no more "...only with C++17 or later." errors.

Best
Andreas
