### ISSUE TITLE
terrain assets published by localhost can not be loaded

### ISSUE THREAD

**Issue by JohnwinJia** [CesiumGS/cesium-unreal#569]
“The Url field can be filled using the same steps as above with http://localhost:portNumber/terrainAsset”
I tried IIS service and it does not work, the 3dtiles data of terrain is producted by CTB.
Strangely, the same data published by a software named "cesiumlab" can be loaded successfully.

![微信截图_20210730120513](https://user-images.githubusercontent.com/88176210/127598631-6c87c03c-2422-4cc0-959b-34bf2cfbd102.png)

![微信截图_20210730120342](https://user-images.githubusercontent.com/88176210/127598559-c5ccbea8-5cb7-41e7-94c3-7b6f45806537.png)

**Comment by kring** [comment]
Please check the Output Log for errors. Most likely IIS has not been configured to serve the .terrain files correctly. It needs to include the response header `Content-Type: application/vnd.quantized-mesh` for the .terrain files, which it will not do by default. I'm closing this because it's unlikely there's any action in cesium-unreal, but please reopen if necessary.
