### ISSUE TITLE
Add gltf 1.0  support ？

### ISSUE THREAD

**Issue by D-WPanda** [CesiumGS/cesium-unreal#595]
Add gltf 1.0  support ？

**Comment by javagl** [comment]
To provide some context (even though it is partially based on guesses) : There are some tilesets "in the wild" that still use glTF 1.0 as their payload in the B3DM tiles. Currently, this just causes an error message

> Only binary glTF version 2 is supported, found version 1 

Right now, there are no plans for a glTF 1.0 support, because the number of tilesets that use glTF 1.0 is decreasing, and this would probably have a bad effort-to-usefulness ratio.

This problem has been reported in some forum threads, for example, in https://community.cesium.com/t/load-3d-tiles-from-external-sources-to-unreal/13193/2 - and a possible workaround is mentioned there as well: The `upgrade` function from https://github.com/CesiumGS/3d-tiles-validator/tree/2.0-tools/tools and be used to upgrade an existing tileset that uses glTF 1.0 to one that uses glTF 2.0. (Note that you have to use the specific `2.0-tools` branch that I linked to).

**Comment by kring** [comment]
I'm closing this as glTF 1.0 was never an official part of the 3D Tiles standard and supporting it would be a significant amount of work, so it's not something to expect to ever do.
