### ISSUE TITLE
In-editor ion token manager

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#598]
Continuing off of this issue in Cesium for Unreal Samples - https://github.com/CesiumGS/cesium-unreal-samples/issues/19

The entire ion token user experience needs to be improved somewhat. Some core issues:

- When tokens update or change, there's no warning for users - tilesets just don't load anymore, which leads users to think the whole plugin broke. Of course, it's still functioning exactly as intended, but that's not clear to users. 
- When tokens change, updating them is laborious, and disrupts user flow. Having to update all tokens on all tilesets and raster overlays in all scenes is a pain. 

Previously, we've discussed centralizing this a little bit, and I think it would really benefit us to push this issue. We should consider implementing a new interface (Maybe in the Cesium panel, above or below the Quick Add assets) where users can set a default token. 

Desired user experience:

- User can set a default token in a Cesium panel somewhere. (Perhaps this auto-populates with the user's token used to add new tilesets. Or it does the first time a user logs in, and users can replace it with a different token if they wish, which will then be used to add new ion assets.)
- If a tileset or raster overlay has a blank token, it will use the default token instead. If a token is set on a specific tileset or raster overlay, that token will take priority over the default token. 
- If a token is not working for a tileset, the UI will indicate this - either in the details panel (preferable) or near the default token in the Cesium panel (Or both?) We really need to make it clear to the user when a token is not working, and give them concise instructions to fix the issue.
- If the user is logged out of ion, show a warning in the Cesium panel that they are not connected to ion, and that online tilesets may not appear correctly. This will hopefully also help users of Cesium Samples to change the token.

There are a few big questions, though:

- Can we detect when a token is invalid in editor?
- Can we detect if a project is using the Cesium for Unreal samples tokens? Maybe we can code in something to compare the token to past Cesium for Unreal Samples tokens, and if it matches, show a warning. While not all plugin users use the samples, enough are building experiences off of the samples that it's worthwhile building in a failsafe to the plugin. 
- Is there a way to make a bigger warning? Like, pop up a new window in the editor to complain about invalid tokens? If users don't click on a tileset or have the Cesium panel open, they still wouldn't see a warning otherwise.

**Comment by kring** [comment]
FWIW, my original design for the Cesium panel included token management capabilities, but I didn't get around to implementing it.
https://miro.com/app/board/o9J_lWkwmOA=/
The design definitely doesn't address all the very good points above, but it might be useful as a starting point.

**Comment by javagl** [comment]
The point of detecting and reporting invalid tokens in general is related to the linked issue, in that it requires a better error reporting mechanism. 

But in the linked issue, there also was that point

> In `cesium-unreal-samples` there might be a dedicated blueprint to handle the case of expired tokens.

But now you mentioned 

> Can we detect if a project is using the Cesium for Unreal samples tokens?

And indeed, the approach of using a blueprint (which was some "initial brainstorming", admittedly) raises some questions:

1. What if a user copies+pastes one of the sample tokens into his "real" application?
2. What if a user manually copies an invalid token into one of the samples?

For 1., there would be no mechanism to tell the user that the problem is related to an expired sample token. For 2., it would report an expired sample token, even though the problem is that the token is otherwise invalid.

So the approach of identifying **THE** sample tokens and adjusting the error messages/handling based on that may allow a more robust solution (with less potential confusion for the end-user).

The general question of default tokens (or updating tokens) has to be sorted out, and one should take care to get this _right_. One (maybe naive?) question is: Would it be possible or sensible to (at least optionally) configure the token with some external `.INI` file or so? Just to make it is possible to update the tokens for dozens of tilesets at once, without editing the project...

    if (exists("tokens.ini")) {
        token = read("tokens.ini", "defaultToken");
    } else {
        token = COMPILE_TIME_DEFAULT_TOKEN;
    }

(In how far something like this can be implemented sensibly (in terms of security) for "real" applications has to be sorted out, but for the sample tokens, this could be handy...)
