### ISSUE TITLE
Expose `maximumCachedBytes` as UProperty

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#633]
By default, Cesium for Unreal caches 512 megabytes of compressed tile data per tileset in memory. This in addition to the decompressed form that will inevitably exist in memory as well, and any raster overlays. And that's just one tileset. On systems without a huge amount of memory, this may result in trying to cache much more than can realistically fit in memory and crashing.

Ideally we'd be smarter about choosing the cache size. Or at least choose a smaller default that's less likely to crash devices with lower memory. But the first, most basic thing we can do is expose the `maxiumCachedBytes` property in `TilesetOptions` as a UProperty on the Tileset. This way people that run into problems are at least able to change it.

**Comment by javagl** [comment]
The forum question that sparked this issue asked for [https://community.cesium.com/t/better-control-over-how-many-tiles-are-loaded-at-any-given-time/15158](Better control over how many tiles are loaded at any given time). The `maximumCachedBytes` are largely unrelated to that, because this does not offer any control about how many tiles are loaded (or how much memory is occupied), but only how much data is *cached*. 

People might still set it to 0 and not observe any effect, because it does not give control over how many tiles are **loaded** at all. People may have to additionally reduce the maximum screen space error or so, to decrease the number of **loaded** tiles.

This is somewhat explained in the doxygen comment, but the exact semantics of this option and the implications of changing it are subtle. Low-level details about the semantics may include the question of whether the cache is purged based on this value *before* or *after* loading newly visible tiles. High-level (user-facing) questions are about the intended usage, or which value to set for this option: When you have 10 tilesets, should you set this value to 256MB/10 for each of them? Should you adjust this value when tilesets are added or removed? ...

But if the goal is to ~"just make it public, let users tweak it, and see whether it prevents crashes", then the PR may already (nearly) solve that. 

(Far more broadly - and maybe we should write an issue for that: Is there any idea about handling `std::bad_alloc` in `cesium-native`?)

**Comment by kring** [comment]
I disagree, the problem mentioned on the forum is very likely to be addressable by tweaking this property. The fundamental issue they want solved is "my program is crashing". And there are also some suggested solutions to what they perceive to be the cause of the problem. But almost certainly the real problem is that there's too much being cached and changing this property will fix it. I also suspect it's not even a lack of memory on the CPU that's the issue, but rather a lack of GPU memory, but that's only a hunch.
