### ISSUE TITLE
Windows Remote Desktop may prevent Cesium actors from loading

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#660]
User reports that when using Remote Desktop connection, Cesium actors won't load in Unreal (though everything else loads fine).

**Comment by DanielAmigo** [comment]
Hello,
indeed, it doesn't work if accessed via RDP. I have tried it on two different machines and neither works: 
- On a Windows Server 2019 user with Unreal Engine 4.27 and the latest version of Cesium
- On a Windows 11 Insider (22494) with the same versions, nor on 4.26. 
On the other hand, on Windows 11, if I login locally (after crashing Unreal Engine and reopening it), I can see the Cesium content perfectly.

If anyone has ideas on how to solve this problem, please share them here. It's quite annoying for me and my colleagues who want to use Cesium remotely from the server.
For any test you may need, count on me.

**Comment by kring** [comment]
I just ran into the same thing. The reason Cesium content doesn't appear under remote desktop is because the Unreal Editor automatically disables real-time mode under remote desktop. And when real-time is disabled, Actors don't get Ticked. And when the Cesium3DTileset Actor doesn't get ticked, tiles don't get loaded and displayed.

I'm not sure what a proper solution is here, but a good workaround is to re-enable real-time rendering. It's an option on the viewport's hamburger menu in the top left.

**Comment by kring** [comment]
This is not something we can fix, and the workaround is documented in [the FAQ](https://cesium.com/learn/unreal/unreal-faq/#why-cant-i-see-my-tilesets-when-i-use-remote-desktop-software) now, so I'm closing this.
