### ISSUE TITLE
CesiumSunSky's Latitude/Longitude/Height properties look editable, but they're not

### ISSUE THREAD

**Issue by CrazyJiajialin** [CesiumGS/cesium-unreal#707]

**Comment by CrazyJiajialin** [comment]
![image](https://user-images.githubusercontent.com/96040952/145762791-94ff92aa-f178-4346-9fe4-b52967ff31ad.png)
![image](https://user-images.githubusercontent.com/96040952/145762813-6782dc55-7d0d-45bf-bae6-0f5dec713e76.png)
The parameters of these components are not changed in the scene after modification, all black.

**Comment by CrazyJiajialin** [comment]
The parameters of the first picture cannot be modified.

**Comment by CrazyJiajialin** [comment]
![image](https://user-images.githubusercontent.com/96040952/145763393-714a6501-e281-4a87-814d-175b551f722a.png)
If you modify parameters such as LAT and log, outputlog displays the error message shown in the preceding figure.

**Comment by kring** [comment]
It's a bit confusing, but those parameters are not meant to be modified. They only show up because of the attached GlobeAnchorComponent, which keeps the CesiumSunSky's origin at the center of the Earth. We should see if there's a way to hide them or at least make it clear that they're not meant to be editable.

**Comment by j9liu** [comment]
Closed by #1530
