### ISSUE TITLE
Add a parameter for inverting Cartographic Polygon

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#721]
Add a parameter to Cesium Polygon Raster Overlay that inverts polygons applied to it (E.G. the effect would apply to everything OUTSIDE the polygon, and not to the interior of the polygon). Users can achieve this effect currently by inverting the mask in the material layer blend, but that's not very user friendly, and leads to unnecessary creation of more materials. 

Adding this would enable a lot of things, such as:

- Hiding everything outside of a predefined boundary, useful for rendering a section of terrain on a table like Project Anywhere, or for combining tilesets where you only need a small part of a certain large tileset
- Adding a material effect like a shadow to the entire tileset except for an area of focus
- Minimizing material count

Also, this should be on the tileset because we would also want it to invert the logic for the `exclude tiles inside` setting.

**Comment by nithinp7** [comment]
Flipping the mask values will be trivial.

The actual tile exclusion outside the polygon should be easy as well. We have a function that can compute the bounding region of a polygon selection and we have a function to convert any tile bounding volume to a bounding region. So we can very easily compute conservatively if a tile is completely outside the polygon. We can do that for each polygon and cull the tile if it is outside for each polygon.

If it fails that test for any of the polygons, then we can do a very similar check as we have currently to see if the tile's bounding region edges intersects any of the polygon edges. If it does then we have to keep the tile since part of the tile may be in the selection. If it doesn't, the tile may be entirely inside or entirely outside. We can check an arbitrary point on the tile bounding region to check if it is inside / outside the polygon, we already do this as well. If the point is outside, then the whole tile bounding volume is outside, so the tile is outside and can be culled.

I think the math should mostly be reusable from the withinPolygons function we have right now.

**Comment by argallegos** [comment]
Added with https://github.com/CesiumGS/cesium-unreal/pull/861
