### ISSUE TITLE
Compilation Error:Math.h(85):[C2059] syntax error:'constant'

### ISSUE THREAD

**Issue by jianxiao1754** [CesiumGS/cesium-unreal#767]
Compiling the latest main branch with following errors:

they are from CesiumUtility/Math.h and CesiumGeospatial/GlobeRectangle.h

![image](https://user-images.githubusercontent.com/55174643/155941230-a64a37d0-fc73-4fab-b30d-81a5387b7d4f.png)

**Comment by kring** [comment]
@jianxiao1754 our CI system reports that the `main` branch is building successfully. My best guess is that you need to update the cesium-native submodule, or need to build/install cesium-native. The latest version of cesium-unreal requires some recent changes to cesium-native.

I'm going to close this because I don't think there's anything to fix, but please reopen if you still think that's a problem with cesium-unreal.
