### ISSUE TITLE
UE5 Preview 2 support

### ISSUE THREAD

**Issue by brandondsantos** [CesiumGS/cesium-unreal#781]
Hi! First off, allow me to say the experimental UE5 plugin added in v1.11.0 was great. However, it appears Unreal has released an update for Unreal Engine 5 -- Preview 2. It fails to load the plugin upon startup and tells me to rebuild it through the IDE. Does anyone know if there is a Cesium update for UE5 Preview 2 in the works or simply a workaround for this issue? Thanks in advance!

**Comment by UnrealVistas** [comment]
I have also had this issue today.

**Comment by kring** [comment]
@brandondsantos @UnrealVistas we believe the plugin will work with Preview 2, it's only the pre-built binaries that are problematic. You may be able to download the preview 1 release zip from GitHub and extract it to your projects Plugins directory instead of to the Engine plugins directory. And then Unreal Engine will compile it when you compile the project. You'll need Visual Studio 2019 installed. If you try this, let me know if it works.

Because it's not possible to produce binaries for a C++ plugin that works with arbitrary UE5 builds, I suggest you avoid upgrading to the latest preview right away when it's released.

I'm planning to get our CI system set up to built Preview 2 binaries of the plugin today, though, so barring any unforeseen difficulties it shouldn't be long.

**Comment by brandondsantos** [comment]
> @brandondsantos @UnrealVistas we believe the plugin will work with Preview 2, it's only the pre-built binaries that are problematic. You may be able to download the preview 1 release zip from GitHub and extract it to your project's Plugins directory instead of to the Engine plugins directory. And then Unreal Engine will compile it when you compile the project. You'll need Visual Studio 2019 installed. If you try this, let me know if it works.
> 
> Because it's not possible to produce binaries for a C++ plugin that works with arbitrary UE5 builds, I suggest you avoid upgrading to the latest preview right away when it's released.
> 
> I'm planning to get our CI system set up to built Preview 2 binaries of the plugin today, though, so barring any unforeseen difficulties it shouldn't be long.

Works on my end. Thanks!

**Comment by UnrealVistas** [comment]
thank you Brandon. Do i create a plugin directory on my project as it doesn't currently appear to have one...?

**Comment by UnrealVistas** [comment]
worked for me thank you :)
