### ISSUE TITLE
Known issues with Cesium for Unreal and UE5

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#810]
The following issues have been observed in Unreal Engine 5 final release:
- [x] ~Physics and collision with Cesium3DTilesets may not behave as expected. https://github.com/CesiumGS/cesium-unreal/issues/809~ Fixed in the final UE5 release.
- [x] ~The "Extend Default Luminance Range in Auto Exposure" option may be missing from the project settings, causing scenes to be bright white. As a workaround, this parameter can be set with the CVAR `r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange = "1"`.~ Fixed in the final UE5 release.
- [x] If you are using the sublevel system (World Composition) from Unreal Engine 4, you may see deprecation warnings. Your levels should still function as expected. #729
- [ ] #488

Any new problems should be added to this list, either in the comments below or by editing the list directly. If there is a corresponding Github issue, please include a link.
You can also [view all Cesium for Unreal issues tagged with the "UE5" label](https://github.com/CesiumGS/cesium-unreal/labels/ue5).

**Comment by astrocoder** [comment]
The UE5 release throws an error when building the binaries:
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Public\Cesium3DTileset.h(351): warning C4996: 'FCesiumExclusionZone': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumEditor\Private\SelectCesiumIonToken.cpp(457): warning C4996: 'UObject::UpdateDefaultConfigFile': TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
[9/15] Link UnrealEditor-CesiumEditor.lib
   Creating library C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Intermediate\Build\Win64\UnrealEditor\Development\CesiumEditor\UnrealEditor-CesiumEditor.lib and object C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Intermediate\Build\Win64\UnrealEditor\Development\CesiumEditor\UnrealEditor-CesiumEditor.exp
[10/15] Compile Module.CesiumRuntime.gen.1_of_3.cpp
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Public\Cesium3DTileset.h(351): warning C4996: 'FCesiumExclusionZone': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
[11/15] Compile Module.CesiumRuntime.cpp
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Public\Cesium3DTileset.h(351): warning C4996: 'FCesiumExclusionZone': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp(1333): warning C4996: 'FCesiumExclusionZone': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp(1345): warning C4996: 'FCesiumExclusionZone': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp(1348): warning C4996: 'FCesiumExclusionZone::West': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp(1349): warning C4996: 'FCesiumExclusionZone::South': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp(1350): warning C4996: 'FCesiumExclusionZone::East': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp(1351): warning C4996: 'FCesiumExclusionZone::North': Exclusion Zones have been deprecated. Please use Cartographic Polygon actor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\CesiumGltfComponent.cpp(755): error C2678: binary '-': no operator found which takes a left-hand operand of type 'FVector3f' (or there is no acceptable conversion)
P:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Math\Vector.h(283): note: could be 'UE::Math::TVector<float> UE::Math::TVector<float>::operator -(const UE::Math::TVector<float> &) const'
P:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Misc\FrameTime.h(226): note: or       'FFrameTime operator -(FFrameTime,FFrameTime)'
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\CesiumGltfComponent.cpp(755): note: while trying to match the argument list '(FVector3f, UE::Math::TVector<double>)'
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\CesiumGltfComponent.cpp(1058): note: see reference to function template instantiation 'void loadPrimitive<CesiumGltf::AccessorView<int8_t>>(LoadPrimitiveResult &,const glm::dmat4x4 &,const CreatePrimitiveOptions &,const CesiumGltf::Accessor &,const CesiumGltf::AccessorView<`anonymous-namespace'::TMeshVector3> &,const TIndexAccessor &)' being compiled
        with
        [
            TIndexAccessor=CesiumGltf::AccessorView<int8_t>
        ]
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\CesiumGltfComponent.cpp(766): error C2678: binary '-': no operator found which takes a left-hand operand of type 'FVector3f' (or there is no acceptable conversion)
P:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Math\Vector.h(283): note: could be 'UE::Math::TVector<float> UE::Math::TVector<float>::operator -(const UE::Math::TVector<float> &) const'
P:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Misc\FrameTime.h(226): note: or       'FFrameTime operator -(FFrameTime,FFrameTime)'
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\CesiumGltfComponent.cpp(766): note: while trying to match the argument list '(FVector3f, UE::Math::TVector<double>)'
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\CesiumGltfComponent.cpp(755): error C2088: '-': illegal for struct
C:\git\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\CesiumGltfComponent.cpp(766): error C2088: '-': illegal for struct
Took 75.5980266s to run UnrealBuildTool.exe, ExitCode=6
UnrealBuildTool failed. See log for more details.

**Comment by j9liu** [comment]
I'm going to close this issue, since we have completely migrated to ue5 and most of these issues have been closed.
