### ISSUE TITLE
Where is the CesiumForUnrealContent folder in ue5 ? 

### ISSUE THREAD

**Issue by softyoda** [CesiumGS/cesium-unreal#820]
I'm trying to match the albedo and roughness with the rest of the scene, but i can't find the material instance location and the documentation seem old.

**Comment by kring** [comment]
Press Ctrl-Space to open the content drawer, click Settings in the top right, and enable both "Show Engine Content" and "Show Plugin Content". Cesium for Unreal content will then show up under All->Engine->Plugins->Cesium for Unreal Content.

I'm closing this because there's no action for us here (the tutorials will be updated for UE5 at some point). In the future, consider posting to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead of a creating a github issue, as we try to use github exclusively for bug reports and feature requests.
