### ISSUE TITLE
If osm has a material, then Cartographic Polygon is invalid

### ISSUE THREAD

**Issue by fonlylovey** [CesiumGS/cesium-unreal#822]
![image](https://user-images.githubusercontent.com/10555898/163973542-39efb19b-bdc3-4894-9b13-b39bec391263.png)
![image](https://user-images.githubusercontent.com/10555898/163973601-51bedd51-9484-4344-822d-46604e823f6f.png)

**Comment by kring** [comment]
Clipping with a Cartographic Polygon is an effect applied by the default material, `/CesiumForUnreal/Materials/Instances/MI_CesiumThreeOverlaysAndClipping`. Since you're replacing the default material with another, you're not getting the clipping effect. But you should be able to copy the default material and modify it to create whatever effect you need.

I'm closing this because I don't think there's any action here. If you want to discuss further, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Comment by fonlylovey** [comment]
ok
