### ISSUE TITLE
Discarding alpha channel from Cesium ion Raster Overlays?

### ISSUE THREAD

**Issue by brandondsantos** [CesiumGS/cesium-unreal#850]
Some of the raster overlays I upload (mainly color + infrared GeoTIFFs from PASDA) to Cesium ion only show the alpha channel when adding them as a base layer of a tileset.  It'd be helpful to have an option to remove the alpha channel or just render RGB channels to prevent encountering this problem.

**Comment by kring** [comment]
@brandondsantos is this specific to Cesium for Unreal, or is it a problem with the Cesium ion tiling that manifests in CesiumJS as well?

**Comment by brandondsantos** [comment]
> @brandondsantos is this specific to Cesium for Unreal, or is it a problem with the Cesium ion tiling that manifests in CesiumJS as well?

I've only seen it happen in Unreal, which is what I'm concerned about.

**Comment by kring** [comment]
Do you mean that you tried it in CesiumJS and it was fine, or do you mean you didn't try CesiumJS because you don't use it? I'm just trying to understand what's going on here. I can't think of any reason Cesium for Unreal would _only_ show the alpha channel, but if Cesium ion isn't interpreting the channels the way you want in the first place, that might make more sense.

By the way, if you truly just want to ignore the alpha channel, that can be done with a custom material layer or material layer blend. This tutorial explains how to work with materials:
https://cesium.com/learn/unreal/unreal-edit-materials/
