### ISSUE TITLE
UE5 - 3D Tiles Don't Load/Unload Correctly with Data Layers/World Partition

### ISSUE THREAD

**Issue by darcyvdd** [CesiumGS/cesium-unreal#858]
I have some Cesium3DTilesets on different levels, for the project we are already utilising Data Layers for different design options within the level. To make this work seamlessly we have different 3D Tiles that are the same terrain but utilise different CesiumCartographicPolygons to cutout precisely around the design and fill-in different areas. We utlisising Data Layers to load/unload the design however the 3D Tiles fail to unload despite being on the DataLayer. It should be noted the if we load/unload the DataLayers in editor, the 3DTiles load/unload appropriately, but in PIE or a packaged build it does not work correctly.

**Comment by kring** [comment]
Thanks for the report @darcyvdd. Can you share a minimal project with us to demonstrate this problem?

**Comment by kring** [comment]
This is likely fixed after #1153, but we should check.

**Comment by kring** [comment]
World Partition and Data Layers appear to work fine, now, with some caveats:

* Tilesets don't work well when "Is Spatially Loaded" is true, because World Partition doesn't seem to be aware of their size/position, so it just never loads them at all.

* If your tileset is parented to the CesiumGeoreference, and the CesiumGeoreference is not in the same data layer as the tileset, then Unreal seems to completely ignore the data layerness of the tileset and just always shows the tileset, no matter the loaded state of the Data Layer. There's an error about it in the log:

> MapCheck: Error: Actor CesiumGeoreference (/Game/DataLayerTest/DataLayerTest) references an actor in a different set of runtime data layers Aerometrex Denver High Resolution 3D Model with Street Level Enhanced 3D (Non-Commercial Trial) 

I used a simple Level Blueprint to test data layers:

<img width="538" alt="image" src="https://github.com/CesiumGS/cesium-unreal/assets/924374/cd599dfb-8f74-4ff3-9ddb-1fb2a2977a4e">
