### ISSUE TITLE
Cull out Raster Terrain tiles with no elevation?

### ISSUE THREAD

**Issue by brandondsantos** [CesiumGS/cesium-unreal#864]
Hi, I need help because I've uploaded a custom Raster Terrain to Cesium ion for use in Cesium for Unreal. Everything works properly, except the only problem is the flat tiles outside of my custom Terrain asset. I want to render a small terrain, without these flat tiles appearing. Does anyone know how I can make this possible?

![raster](https://user-images.githubusercontent.com/29965024/170585339-abf3ad56-29e4-40f0-ae4f-ef3e268f4b5b.png)

**Comment by kring** [comment]
When uploading your terrain data, choose Cesium World Terrain as the base. Ion will blend your terrain with CWT at the edges. There's currently no way to show "nothing" outside the area of your terrain data.

I'm going to close this because there's not really anything to do in Cesium for Unreal. Please start a community forum thread if you want to discuss further.
