### ISSUE TITLE
ue4-main branch compilation throws "The CesiumForUnreal plugin was designed for build 4.26.0" error on UE4 4.27.2 Ubuntu

### ISSUE THREAD

**Issue by ankitatcodingnebula** [CesiumGS/cesium-unreal#869]
Hello Cesium Team,

I am on Ubuntu 20.04 and have built UE4 4.27.2. I was successfully able to build and compile the ue4-main branch. But when I start my project I get the error:

`The CesiumForUnreal plugin was designed for build 4.26.0`

and fails to load the project.

Please suggest.

**Comment by kring** [comment]
You usually just need to say "yes" to that popup to continue loading the plugin, and it will work fine. Or, change the version in CesiumForUnreal.uproject and it will no longer prompt.

I'm going to close this, but if you're still having trouble, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Comment by ankitatcodingnebula** [comment]
@kring Thanks for the response. As per your advise I changed the "EngineVersion" in .uplugin file to 4.27.0. This removed the above error but now I get "Missing CesiumEditor and CesiumRuntime" error. I followed the ticket here https://github.com/CesiumGS/cesium-unreal/issues/692 but it did not help. Any suggestions?

**Comment by kring** [comment]
@ankitatcodingnebula can you use pre-built binaries instead of building it yourself? You can find them on the Releases page:
https://github.com/CesiumGS/cesium-unreal/releases

If you do need to built the plugin yourself, you will need to carefully follow the developer setup instructions:
https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup.md

The best place to get help with this sort of thing is on the community forum. We use GitHub issues exclusively for bug reports and feature requests.
