### ISSUE TITLE
request failed, libcurl error: 35 (SSL connect error)

### ISSUE THREAD

**Issue by NCHUPJ** [CesiumGS/cesium-unreal#877]
![image](https://user-images.githubusercontent.com/26161634/173313287-6843a245-7be8-4845-b250-8d88cac6c114.png)

**Comment by kring** [comment]
Some things to check:
1. If this is your own project, does the Cesium for Unreal Samples project work?
2. Do you have a proxy on your network that might be interfering with connections to ecn.t0.tiles.virtualearth.net?
3. Does your project include a version of OpenSSL other than the one bundled with Unreal Engine? It could be included in a plugin or linked against your game code.

I'm going to close this because there's likely nothing we can fix in Cesium for Unreal. But please followup on the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) if you figure it out or if you have new information that might help diagnose it.
