### ISSUE TITLE
Crash when switching levels with an invalid project token

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#879]
1. Open Cesium for Unreal Samples.
2. In the Cesium UI, click the Token button.
3. Select "Specify a token" and then enter some random characters to create an invalid token, and click "Use as Project Default Token".
4. A panel will pop up explaining that the token is invalid and offering to help fix it. Click the X to close the panel.
5. From the Content Draw, open another level.
6. Unreal Engine crashes.

Note that this can also happen without the "token is invalid" popup at step 4 if the token is valid for the resources on the current level,  but invalid for the ones on the new level, e.g. because the token isn't authorized for those assets, or because those assets haven't been added to the user's account from the Asset Depot.

**Comment by baothientran** [comment]
I'm still trying to figure out why Unreal 5 tries to load a new tileset actor and then remove the actor right away when switching level. But the crash is that:
- When switching to a new level, Unreal loads the new tileset actor and because the token is incorrect, `LoadErrorCallback` of `TilesetOptions` will be scheduled in the main thread after loading
- But then, once the actor is finished loading, it is destroyed immediately by garbage collector, which will trigger Cesium Native Tilese destructor and `AActor::BeginDestroy()`. When tileset destructor get called, it also try to flush any of the remaining tasks in the AsyncSystem, which will trigger the error callback above. The problem is the error callback also schedules a GameThread task that refers to the currently destroyed actor (https://github.com/CesiumGS/cesium-unreal/blob/9b07799e929309005e6212a14a391a60da1771f8/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L862). When the task is triggered, it will lead to crash.
