### ISSUE TITLE
How to convert cesium world terrain to landscape in UE

### ISSUE THREAD

**Issue by firstgle** [CesiumGS/cesium-unreal#932]
Hi All,
  I want to use water plugin in my ue level, but this plugin must be used with UE landscape. how can I use the water plugin with Cesium world terrain instead of landscape.
  
  Gonglaien

Thank you in adavace!

**Comment by kring** [comment]
Cesium terrain can't be converted to landscape, but you can use water. Please see the material tutorial:
https://cesium.com/learn/unreal/unreal-edit-materials/

And post any follow-up questions on the community forum:
https://community.cesium.com/c/cesium-for-unreal/10

**Comment by ChrisPanagogian** [comment]
Hi,
Does anyone know if there is any way to apply buoyancy in cesium water. I ask because water system plugin of unreal need a landscape so as to work and in this way cesium terrain become awful. Secondly I would like to know if anybody had applied Physical Water Surface plugin, in cesium terrain, and if yes did he have good results as regards buoyancy;
Thank you!
