### ISSUE TITLE
World Partition resulting in editor crash with Cesium

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#941]
Observed here: https://community.cesium.com/t/ue5-crash-when-editing-deleting-saving-cartographic-polygon/19824

User reported that saving a scene while both World Partition and the Cesium for Unreal plugin resulted in a crash. While Cesium for Unreal is not compatible with World Partition, this should probably not be resulting in a crash.

The user first noticed this issue when attempting to save a scene after adding a Cartographic Polygon. They provided this log:
`Fatal error: [File:D:\build++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\Templates\Casts.cpp] [Line: 10] Cast of CesiumCartographicPolygon /Game/Seattle_Project/Levels/Cesium-BingMapAerial.Cesium-BingMapAerial:PersistentLevel.CesiumCartographicPolygon_UAID_3CECEF77A2E62E2901_1946255554 to MetaData failed`

I am unable to reproduce this on my machine. However, the user has experienced it on multiple machines, in multiple projects, including fresh projects. All the user's machines are using RTX3090 GPUs.

**Comment by BPXXX** [comment]
Had same question,then I created a new Level using basic template to replace my older Level, UE5 stops crashing!

**Comment by ligaofeng0901** [comment]
Same question. Add any actor of Cesium-Unreal in a map with world partition, then the actor can't be deleted. If do the delete operation, the editor crashes. Yes, my GPU also is RTX3090.

**Comment by nithinp7** [comment]
Just ran into this in 5.1 (but it's likely I just never noticed it in 5.0). I doubt this has anything to do with the graphics card - I have a GTX 1650. We don't currently use world partition and in fact world partition probably does not work with georeference origin changes, but it shouldn't crash. Steps to reproduce afaict:

Open the template "Open World" level.
- Add Cesium World Terrain (I imagine any tileset works).
- Save the level and switch to another level, even double clicking on the same level in the asset browser should cause the issue to happen.
- If the crash doesn't happen yet, switch back to the level and try switching away again.

The crash stack trace seems to indicate that the world partition system is trying to unload some actor (I assume the tileset) and failing some cast along the way. The world partition system should not have to interact with tilesets, since tilesets should be loaded all the time, but maybe there's something else we need to specify on the tileset actors to let Unreal know that.

**Comment by wyd111** [comment]
create a buleprit inherited Cesium3DTileset can slove this prolbem, but i don't know what happend

**Comment by ligaofeng0901** [comment]
> create a buleprint inherited Cesium3DTileset replace with Cesium3DTileset can slove this prolbem, but i don't know what happend

It works!  But why?🤔

**Comment by ubplan007** [comment]
> 
Hi Expert
I am struggling with the same problem. Can you explain in more detail how to solve the problem?
