### ISSUE TITLE
Globe Anchor Component - Allow for rotational offset as parameter and getting rotations from anchor component modified actors. 

### ISSUE THREAD

**Issue by CesiumBen** [CesiumGS/cesium-unreal#943]
For the [5th VR tutorial ](https://github.com/CesiumGS/cesium-unreal-vr-tutorial/issues/5) about dragging the globe it would be great if we could pass in a rotational offset to the SnapLocalUpToEllipsoidNormal function to allow for more control. This is so we could point a VR player downward to face the globe for example. With snapping taking total control of the actors rotation, that other layer of control would he helpful.

As a utility it would also be helpful to do the inverse and get a rotation from the owning actor, which is modified by whatever rotation is applied to the actor to make it along the normal of the ellipsoid.

**Comment by xuelongmu** [comment]
To add some additional clarity: we don't necessarily have to add another parameter to the existing function. We are just looking for an interface to set and control the user's rotation relative to the globe, rather than the current behavior of always snapping them to the ellipsoid normal orientation. So something like `RotationOffset` parameter and `SetRotationOffset` function that can be used to animate the rotation at runtime if needed.

**Comment by kring** [comment]
The GlobeAnchorComponent in Cesium for Unity allows users to specify a rotation as Euler angles relative to the default East-South-Up frame. Something like that would be useful in Unreal as well.
