### ISSUE TITLE
Can we replace Spline with Mesh in CartographicPolygon

### ISSUE THREAD

**Issue by leozejia** [CesiumGS/cesium-unreal#991]
we want to use CartographicPolygon to transparent some area,but spline can't make a hole,is that possible to use mesh in this situation?

**Comment by kring** [comment]
This issue is pretty old, but if you're still having trouble, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) and tell us more about what you're trying to accomplish. Depending on the details, you might be asking for a way to create polygons with holes in a Cartographic Polygon. Or perhaps you're asking for the ability to exclude a truly 3D shape. But I'm going to close this because it's not actionable as-is.
